-- ============================================================================
-- Migration V14: Add VNPay IPN Attempts, Raw Receipts, Events, Cases and Alerts
-- ============================================================================

-- 1. Mở rộng check constraint cho payment_method
ALTER TABLE payments DROP CONSTRAINT IF EXISTS ck_payments_method;
ALTER TABLE payments ADD CONSTRAINT ck_payments_method
    CHECK (payment_method IN ('COD_MOCK', 'BANK_TRANSFER_MOCK', 'E_WALLET_MOCK', 'VNPAY'));

-- 2. Bổ sung trạng thái UNDER_REVIEW cho orders
ALTER TABLE orders DROP CONSTRAINT IF EXISTS ck_orders_status;
ALTER TABLE orders ADD CONSTRAINT ck_orders_status CHECK (status IN (
    'PAYMENT_PENDING', 'PAID_HELD', 'SELLER_CONFIRMED', 'SHIPPED', 'DELIVERED',
    'COMPLETED', 'CANCELLED', 'DISPUTED', 'REFUNDED', 'UNDER_REVIEW'
));

-- 3. Bổ sung trạng thái UNDER_REVIEW cho payments
ALTER TABLE payments DROP CONSTRAINT IF EXISTS ck_payments_status;
ALTER TABLE payments ADD CONSTRAINT ck_payments_status CHECK (status IN (
    'PENDING', 'PAID', 'HELD', 'RELEASED', 'REFUND_PENDING', 'REFUNDED', 'FAILED', 'UNDER_REVIEW'
));

-- 4. Cập nhật ràng buộc toàn vẹn các trường trạng thái của payments (ck_payments_state_fields)
-- Định nghĩa rõ: UNDER_REVIEW có paid_at (tiền đã trừ) nhưng held_at NULL (chưa vào escrow).
-- Cho phép REFUND_PENDING và REFUNDED xuất phát từ UNDER_REVIEW (held_at IS NULL) hoặc từ HELD (held_at IS NOT NULL).
ALTER TABLE payments DROP CONSTRAINT IF EXISTS ck_payments_state_fields;
ALTER TABLE payments ADD CONSTRAINT ck_payments_state_fields CHECK (
    (status = 'PENDING' AND paid_at IS NULL AND held_at IS NULL AND released_at IS NULL AND refunded_at IS NULL AND failure_reason IS NULL)
    OR
    (status = 'PAID' AND paid_at IS NOT NULL AND held_at IS NULL AND released_at IS NULL AND refunded_at IS NULL AND failure_reason IS NULL)
    OR
    (status = 'HELD' AND paid_at IS NOT NULL AND held_at IS NOT NULL AND held_at >= paid_at AND released_at IS NULL AND refunded_at IS NULL AND failure_reason IS NULL)
    OR
    (status = 'RELEASED' AND paid_at IS NOT NULL AND held_at IS NOT NULL AND held_at >= paid_at AND released_at IS NOT NULL AND released_at >= held_at AND refunded_at IS NULL AND failure_reason IS NULL)
    OR
    (status = 'UNDER_REVIEW' AND payment_method = 'VNPAY' AND paid_at IS NOT NULL AND held_at IS NULL AND released_at IS NULL AND refunded_at IS NULL AND failure_reason IS NULL)
    OR
    (status = 'REFUND_PENDING' AND paid_at IS NOT NULL AND ((payment_method = 'VNPAY' AND held_at IS NULL) OR (held_at IS NOT NULL AND held_at >= paid_at)) AND released_at IS NULL AND refunded_at IS NULL AND refund_amount IS NOT NULL AND refund_reason IS NOT NULL AND failure_reason IS NULL)
    OR
    (status = 'REFUNDED' AND paid_at IS NOT NULL AND ((payment_method = 'VNPAY' AND held_at IS NULL) OR (held_at IS NOT NULL AND held_at >= paid_at)) AND released_at IS NULL AND refunded_at IS NOT NULL AND (held_at IS NULL OR refunded_at >= held_at) AND refund_amount IS NOT NULL AND refund_reason IS NOT NULL AND failure_reason IS NULL)
    OR
    (status = 'FAILED' AND paid_at IS NULL AND held_at IS NULL AND released_at IS NULL AND refunded_at IS NULL AND failure_reason IS NOT NULL)
);

-- 5. Thêm composite unique trên payments để hỗ trợ composite foreign key
ALTER TABLE payments ADD CONSTRAINT uq_payments_payment_order UNIQUE (payment_id, order_id);

-- 6. Tạo bảng lưu lịch sử các lần thử thanh toán (Attempts)
CREATE TABLE payment_attempts (
    attempt_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                BIGINT NOT NULL,
    payment_id              BIGINT NOT NULL,
    txn_ref                 VARCHAR(100) NOT NULL UNIQUE,
    amount                  NUMERIC(19,2) NOT NULL,
    currency                CHAR(3) NOT NULL DEFAULT 'VND',
    provider                VARCHAR(30) NOT NULL DEFAULT 'VNPAY',
    status                  VARCHAR(35) NOT NULL DEFAULT 'PENDING',
    vnp_amount_raw          BIGINT,
    vnp_amount              NUMERIC(19,2),
    vnp_transaction_no      VARCHAR(100),
    vnp_response_code       VARCHAR(10),
    vnp_transaction_status  VARCHAR(10),
    vnp_bank_code           VARCHAR(50),
    vnp_pay_date            VARCHAR(20),
    failure_reason          VARCHAR(500),
    ipn_count               INT NOT NULL DEFAULT 0,
    first_ipn_received_at   TIMESTAMPTZ,
    last_ipn_received_at    TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ,

    CONSTRAINT fk_attempt_payment_order FOREIGN KEY (payment_id, order_id)
        REFERENCES payments (payment_id, order_id) ON DELETE RESTRICT,
    CONSTRAINT ck_attempt_amount CHECK (amount > 0),
    CONSTRAINT ck_attempt_currency CHECK (currency = 'VND'),
    CONSTRAINT ck_attempt_status CHECK (status IN (
        'PENDING',
        'SUCCESS',
        'FAILED',
        'SUPERSEDED',
        'EXPIRED',
        'SUCCESS_ON_EXPIRED_ORDER',
        'SUCCESS_DUPLICATE_CHARGE',
        'FLAGGED_SUSPICIOUS',
        'SUCCESS_PENDING_REVIEW'
    ))
);

CREATE INDEX ix_payment_attempts_order_id ON payment_attempts(order_id);
CREATE UNIQUE INDEX uq_payment_attempts_single_pending
    ON payment_attempts(payment_id) WHERE status = 'PENDING';

-- 7. Bảng ghi nhận Raw HTTP Request tiếp nhận tại Controller (payment_ipn_raw_receipts)
CREATE TABLE payment_ipn_raw_receipts (
    receipt_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_query_params            TEXT NOT NULL,
    raw_query_original_length   INT NOT NULL,
    raw_query_truncated         BOOLEAN NOT NULL DEFAULT FALSE,
    raw_query_sanitized         BOOLEAN NOT NULL DEFAULT FALSE,
    raw_query_sha256            CHAR(64) NOT NULL,
    ip_address                  VARCHAR(50),
    received_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    vnp_txn_ref                 VARCHAR(100),       -- Dữ liệu forensic chưa tin cậy
    vnp_transaction_no          VARCHAR(100),       -- Dữ liệu forensic chưa tin cậy
    vnp_amount_text             TEXT,               -- Chuỗi thô nhận được, không ép kiểu số
    verification_status         VARCHAR(30) NOT NULL DEFAULT 'UNVERIFIED',
    processing_status           VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    processing_error            VARCHAR(200),

    CONSTRAINT ck_receipt_verification_status CHECK (verification_status IN (
        'UNVERIFIED', 'MALFORMED_REQUEST', 'SIGNATURE_INVALID', 'SIGNATURE_VALID_UNLINKED', 'LINKED'
    )),
    CONSTRAINT ck_receipt_processing_status CHECK (processing_status IN (
        'RECEIVED', 'PROCESSED', 'PROCESSING_FAILED', 'RETRYABLE_ERROR'
    )),
    -- Ràng buộc toàn vẹn kích thước và trạng thái query
    CONSTRAINT ck_receipt_char_length CHECK (char_length(raw_query_params) <= 8192),
    CONSTRAINT ck_receipt_length_consistency CHECK (
        (NOT raw_query_truncated AND char_length(raw_query_params) = raw_query_original_length)
        OR
        (raw_query_truncated AND char_length(raw_query_params) < raw_query_original_length)
    ),
    CONSTRAINT ck_receipt_truncation_status CHECK (
        NOT (raw_query_truncated OR raw_query_sanitized)
        OR verification_status IN ('UNVERIFIED', 'MALFORMED_REQUEST')
    ),
    CONSTRAINT ck_receipt_verified_integrity CHECK (
        verification_status NOT IN ('SIGNATURE_VALID_UNLINKED', 'LINKED')
        OR (NOT raw_query_truncated AND NOT raw_query_sanitized AND raw_query_params ~ '^[ -~]*$')
    )
);

CREATE INDEX ix_raw_receipts_txn_ref ON payment_ipn_raw_receipts(vnp_txn_ref);
CREATE INDEX ix_raw_receipts_status ON payment_ipn_raw_receipts(processing_status, received_at);

-- 8. Bảng lưu sự kiện IPN đã qua kiểm tra cấu trúc, xác thực chữ ký và liên kết attempt
CREATE TABLE payment_ipn_events (
    event_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id              BIGINT NOT NULL UNIQUE REFERENCES payment_ipn_raw_receipts(receipt_id) ON DELETE RESTRICT,
    attempt_id              BIGINT NOT NULL REFERENCES payment_attempts(attempt_id) ON DELETE RESTRICT,
    order_id                BIGINT NOT NULL,
    payment_id              BIGINT NOT NULL,
    txn_ref                 VARCHAR(100) NOT NULL,
    vnp_transaction_no      VARCHAR(100),
    vnp_response_code       VARCHAR(10),
    vnp_transaction_status  VARCHAR(10),
    vnp_curr_code           VARCHAR(10),
    vnp_amount_text         TEXT,
    vnp_amount_raw          BIGINT,
    vnp_amount              NUMERIC(19,2),
    vnp_bank_code           VARCHAR(50),
    vnp_bank_tran_no        VARCHAR(100),
    vnp_card_type           VARCHAR(20),
    vnp_pay_date            VARCHAR(20),
    ip_address              VARCHAR(50),
    processing_outcome      VARCHAR(50) NOT NULL,
    received_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_ipn_events_amount CHECK (
        processing_outcome IN ('REJECTED_AMOUNT_MISMATCH')
        OR (vnp_amount_raw IS NOT NULL AND vnp_amount IS NOT NULL)
    ),
    CONSTRAINT ck_ipn_events_outcome CHECK (processing_outcome IN (
        'APPLIED_SUCCESS', 'APPLIED_FAILED', 'DUPLICATE_ACKNOWLEDGED', 'CONFLICT_IGNORED',
        'CONFLICT_CHARGE_REQUIRES_RECONCILIATION', 'FLAGGED_SUSPICIOUS', 'APPLIED_EXPIRED_ORDER',
        'APPLIED_DUPLICATE_CHARGE', 'APPLIED_PENDING_REVIEW', 'REJECTED_AMOUNT_MISMATCH', 'REJECTED_CURRENCY_MISMATCH'
    ))
);

CREATE INDEX ix_payment_ipn_events_attempt_id ON payment_ipn_events(attempt_id);
CREATE INDEX ix_payment_ipn_events_txn_ref ON payment_ipn_events(txn_ref);

-- 9. Bảng lưu vết thẩm định UNDER_REVIEW (Audit Log Vận Hành)
CREATE TABLE payment_review_audits (
    review_audit_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE RESTRICT,
    payment_id              BIGINT NOT NULL REFERENCES payments(payment_id) ON DELETE RESTRICT,
    attempt_id              BIGINT REFERENCES payment_attempts(attempt_id) ON DELETE RESTRICT,
    decided_by              VARCHAR(50) NOT NULL,
    decision                VARCHAR(30) NOT NULL,
    reason_note             TEXT NOT NULL,
    vnp_verification_ref    VARCHAR(100),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_review_decision CHECK (decision IN ('APPROVED_SAFE', 'REJECTED_FRAUD'))
);

CREATE INDEX ix_payment_review_audits_order_id ON payment_review_audits(order_id);
CREATE INDEX ix_payment_review_audits_payment_id ON payment_review_audits(payment_id);

-- 10. Hàng đợi Đối soát Bền vững (payment_reconciliation_cases)
CREATE TABLE payment_reconciliation_cases (
    case_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE RESTRICT,
    payment_id              BIGINT NOT NULL REFERENCES payments(payment_id) ON DELETE RESTRICT,
    attempt_id              BIGINT REFERENCES payment_attempts(attempt_id) ON DELETE RESTRICT,
    case_type               VARCHAR(40) NOT NULL,
    status                  VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    source_type             VARCHAR(30) NOT NULL,
    event_id                BIGINT REFERENCES payment_ipn_events(event_id) ON DELETE RESTRICT,
    review_audit_id         BIGINT REFERENCES payment_review_audits(review_audit_id) ON DELETE RESTRICT,
    vnp_transaction_no      VARCHAR(100),
    dedup_key               VARCHAR(150) NOT NULL UNIQUE,
    assigned_to             VARCHAR(50),
    resolution_note         TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at             TIMESTAMPTZ,

    CONSTRAINT ck_rec_case_type CHECK (case_type IN (
        'EXPIRED_ORDER', 'DUPLICATE_CHARGE', 'LATE_SUCCESS_ON_FAILED', 'MISMATCH_CHARGE', 'REFUND_PENDING'
    )),
    CONSTRAINT ck_rec_source_type CHECK (source_type IN ('IPN_EVENT', 'REVIEW_DECISION')),
    CONSTRAINT ck_rec_status CHECK (status IN ('OPEN', 'RESOLVED')),
    CONSTRAINT ck_rec_source_fk CHECK (
        (source_type = 'IPN_EVENT' AND event_id IS NOT NULL AND review_audit_id IS NULL)
        OR
        (source_type = 'REVIEW_DECISION' AND review_audit_id IS NOT NULL AND event_id IS NULL)
    ),
    CONSTRAINT ck_rec_type_source_combination CHECK (
        (case_type = 'REFUND_PENDING' AND source_type = 'REVIEW_DECISION')
        OR
        (case_type IN ('EXPIRED_ORDER', 'DUPLICATE_CHARGE', 'LATE_SUCCESS_ON_FAILED', 'MISMATCH_CHARGE') AND source_type = 'IPN_EVENT')
    )
);

CREATE INDEX ix_rec_cases_status ON payment_reconciliation_cases(status, case_type);

-- 11. Bảng Outbox Cảnh báo Bất thường (payment_alert_requests)
CREATE TABLE payment_alert_requests (
    alert_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id                 BIGINT NOT NULL UNIQUE REFERENCES payment_reconciliation_cases(case_id) ON DELETE RESTRICT,
    alert_type              VARCHAR(50) NOT NULL,
    severity                VARCHAR(20) NOT NULL,
    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count           INT NOT NULL DEFAULT 0,
    last_error              TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at                 TIMESTAMPTZ,

    CONSTRAINT ck_alert_status CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE INDEX ix_alert_requests_pending ON payment_alert_requests(status, created_at);
