-- G01/G02. Existing V14 accounts retain their provenance; no KTV approval is invented.
CREATE FUNCTION og_reject_history_mutation() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = '23514';
END;
$$;

CREATE FUNCTION og_has_role(p_user BIGINT, p_role TEXT) RETURNS BOOLEAN
LANGUAGE sql STABLE SET search_path FROM CURRENT AS $$
    SELECT EXISTS (SELECT 1 FROM user_roles ur JOIN roles r USING(role_id) JOIN users u USING(user_id)
                   WHERE ur.user_id = p_user AND r.role_name = p_role AND u.status='ACTIVE' AND u.deleted_at IS NULL)
$$;

ALTER TABLE users
    ADD COLUMN email_verified_at TIMESTAMPTZ,
    ADD COLUMN identity_workflow VARCHAR(20) NOT NULL DEFAULT 'LEGACY_V14',
    ADD CONSTRAINT ck_users_identity_workflow CHECK (identity_workflow IN ('LEGACY_V14','UC83'));

CREATE TABLE user_security_settings (
    user_id BIGINT PRIMARY KEY REFERENCES users(user_id),
    email_2fa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    verified_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (NOT email_2fa_enabled OR verified_at IS NOT NULL)
);

CREATE TABLE auth_challenges (
    challenge_id UUID PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id),
    subject_key VARCHAR(360) NOT NULL CHECK (btrim(subject_key) <> ''),
    purpose VARCHAR(30) NOT NULL CHECK (purpose IN
        ('REGISTER_EMAIL','PASSWORD_RESET','LOGIN_EMAIL_2FA','CHANGE_PHONE','SECURITY_SETTING')),
    code_digest VARCHAR(128) NOT NULL CHECK (length(code_digest) >= 32),
    state VARCHAR(15) NOT NULL DEFAULT 'OPEN' CHECK (state IN ('OPEN','CONSUMED','INVALIDATED')),
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    next_send_at TIMESTAMPTZ NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    consumed_at TIMESTAMPTZ,
    invalidated_at TIMESTAMPTZ,
    command_key VARCHAR(150) NOT NULL UNIQUE,
    CHECK (expires_at > issued_at AND next_send_at >= issued_at),
    CHECK (max_attempts BETWEEN 1 AND 15 AND attempt_count BETWEEN 0 AND max_attempts),
    CHECK (purpose = 'REGISTER_EMAIL' OR user_id IS NOT NULL),
    CHECK ((state = 'OPEN' AND consumed_at IS NULL AND invalidated_at IS NULL)
        OR (state = 'CONSUMED' AND consumed_at IS NOT NULL AND invalidated_at IS NULL)
        OR (state = 'INVALIDATED' AND consumed_at IS NULL AND invalidated_at IS NOT NULL))
);
-- Expired OPEN challenges must be invalidated before issuing a replacement.
CREATE UNIQUE INDEX uq_auth_challenges_open ON auth_challenges(subject_key,purpose) WHERE state='OPEN';
CREATE INDEX ix_auth_challenges_expiry ON auth_challenges(expires_at) WHERE state='OPEN';

CREATE TABLE ekyc_profiles (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    revision_no INTEGER NOT NULL CHECK (revision_no > 0),
    state VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
        CHECK (state IN ('DRAFT','IN_PROGRESS','PENDING','VERIFIED','REJECTED','EXPIRED')),
    submitted_data JSONB NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(submitted_data)='object'),
    ai_summary JSONB NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(ai_summary)='object'),
    nonmatch_count INTEGER NOT NULL DEFAULT 0 CHECK (nonmatch_count BETWEEN 0 AND 15),
    last_nonmatch_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_at TIMESTAMPTZ,
    verified_at TIMESTAMPTZ,
    reference_expires_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    UNIQUE(user_id,revision_no),
    UNIQUE(profile_id,user_id),
    CHECK (state NOT IN ('PENDING','VERIFIED','REJECTED') OR submitted_at IS NOT NULL),
    CHECK (state <> 'VERIFIED' OR (verified_at IS NOT NULL AND reference_expires_at IS NOT NULL
        AND reference_expires_at > verified_at AND reference_expires_at <= verified_at + INTERVAL '3 months'))
);
CREATE UNIQUE INDEX uq_ekyc_one_active ON ekyc_profiles(user_id)
    WHERE state IN ('DRAFT','IN_PROGRESS','PENDING');
CREATE INDEX ix_ekyc_work_queue ON ekyc_profiles(state,submitted_at,profile_id);

CREATE TABLE identity_document_registry (
    document_digest CHAR(64) PRIMARY KEY CHECK (document_digest ~ '^[0-9a-f]{64}$'),
    digest_key_version VARCHAR(40) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    first_profile_id BIGINT NOT NULL,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(document_digest,user_id),
    FOREIGN KEY(first_profile_id,user_id) REFERENCES ekyc_profiles(profile_id,user_id)
);
COMMENT ON COLUMN identity_document_registry.document_digest IS
    'Keyed digest/HMAC of normalized document ID. Keep old identities; no plaintext CCCD or unkeyed hash.';
CREATE TRIGGER trg_identity_registry_immutable BEFORE UPDATE OR DELETE ON identity_document_registry
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
ALTER TABLE ekyc_profiles ADD COLUMN document_digest CHAR(64),
    ADD CONSTRAINT fk_ekyc_document_owner FOREIGN KEY(document_digest,user_id)
        REFERENCES identity_document_registry(document_digest,user_id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE ekyc_private_assets (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES ekyc_profiles(profile_id),
    asset_type VARCHAR(20) NOT NULL CHECK (asset_type IN ('CARD_FRONT','CARD_BACK','LIVE_FRAME','REFERENCE')),
    object_key TEXT NOT NULL CHECK (btrim(object_key) <> '' AND object_key !~ '^https?://'),
    content_digest CHAR(64) NOT NULL CHECK (content_digest ~ '^[0-9a-f]{64}$'),
    captured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ,
    CHECK (expires_at > captured_at AND expires_at <= captured_at + INTERVAL '3 months'),
    CHECK (deleted_at IS NULL OR deleted_at >= captured_at)
);
CREATE INDEX ix_ekyc_asset_expiry ON ekyc_private_assets(expires_at) WHERE deleted_at IS NULL;

CREATE TABLE ekyc_verification_attempts (
    attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES ekyc_profiles(profile_id),
    result VARCHAR(20) NOT NULL CHECK (result IN ('MATCH','NON_MATCH','SERVICE_ERROR','MANUAL_REVIEW')),
    model_metadata JSONB NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(model_metadata)='object'),
    fallback_authorized_by BIGINT REFERENCES users(user_id),
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    command_key VARCHAR(150) NOT NULL UNIQUE,
    CHECK ((result='MANUAL_REVIEW') = (fallback_authorized_by IS NOT NULL))
);
CREATE FUNCTION og_guard_ekyc_attempt() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE p ekyc_profiles;
BEGIN
    SELECT * INTO STRICT p FROM ekyc_profiles WHERE profile_id=NEW.profile_id FOR UPDATE;
    IF p.state NOT IN ('DRAFT','IN_PROGRESS') THEN
        RAISE EXCEPTION 'eKYC input is closed' USING ERRCODE='23514';
    END IF;
    NEW.attempted_at := clock_timestamp();
    IF NEW.result='MANUAL_REVIEW' AND NOT og_has_role(NEW.fallback_authorized_by,'ADMIN') THEN
        RAISE EXCEPTION 'Manual fallback requires Admin' USING ERRCODE='23514';
    END IF;
    IF NEW.result='NON_MATCH' THEN
        IF p.nonmatch_count >= 15 OR
           (p.last_nonmatch_at IS NOT NULL AND NEW.attempted_at < p.last_nonmatch_at + INTERVAL '3 seconds') THEN
            RAISE EXCEPTION 'eKYC attempt limit/cooldown' USING ERRCODE='23514';
        END IF;
        UPDATE ekyc_profiles SET nonmatch_count=nonmatch_count+1,last_nonmatch_at=NEW.attempted_at
            WHERE profile_id=p.profile_id;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_ekyc_attempt_guard BEFORE INSERT ON ekyc_verification_attempts
    FOR EACH ROW EXECUTE FUNCTION og_guard_ekyc_attempt();
CREATE TRIGGER trg_ekyc_attempt_history BEFORE UPDATE OR DELETE ON ekyc_verification_attempts
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();

CREATE TABLE ekyc_decisions (
    decision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL UNIQUE REFERENCES ekyc_profiles(profile_id),
    reviewed_by BIGINT NOT NULL REFERENCES users(user_id),
    outcome VARCHAR(10) NOT NULL CHECK (outcome IN ('VERIFIED','REJECTED')),
    reason TEXT,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    command_key VARCHAR(150) NOT NULL UNIQUE,
    CHECK (outcome <> 'REJECTED' OR NULLIF(btrim(reason),'') IS NOT NULL)
);
CREATE FUNCTION og_apply_ekyc_decision() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE p ekyc_profiles;
BEGIN
    NEW.decided_at:=clock_timestamp();
    SELECT * INTO STRICT p FROM ekyc_profiles WHERE profile_id=NEW.profile_id FOR UPDATE;
    IF p.state<>'PENDING' OR NOT og_has_role(NEW.reviewed_by,'KTV') THEN
        RAISE EXCEPTION 'Only KTV can decide a pending eKYC revision' USING ERRCODE='23514';
    END IF;
    IF NEW.outcome='VERIFIED' AND (
        p.document_digest IS NULL
        OR (SELECT count(DISTINCT asset_type) FROM ekyc_private_assets
            WHERE profile_id=p.profile_id AND deleted_at IS NULL AND expires_at>NEW.decided_at
              AND asset_type IN ('CARD_FRONT','CARD_BACK','LIVE_FRAME','REFERENCE')) <> 4) THEN
        RAISE EXCEPTION 'eKYC identity/private evidence incomplete' USING ERRCODE='23514';
    END IF;
    UPDATE ekyc_profiles SET state=NEW.outcome,
        verified_at=CASE WHEN NEW.outcome='VERIFIED' THEN NEW.decided_at END,
        reference_expires_at=CASE WHEN NEW.outcome='VERIFIED' THEN
            LEAST(NEW.decided_at+INTERVAL '3 months',
                (SELECT min(expires_at) FROM ekyc_private_assets WHERE profile_id=p.profile_id AND deleted_at IS NULL)) END,
        version=version+1 WHERE profile_id=p.profile_id;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_ekyc_decision_apply BEFORE INSERT ON ekyc_decisions
    FOR EACH ROW EXECUTE FUNCTION og_apply_ekyc_decision();
CREATE TRIGGER trg_ekyc_decisions_history BEFORE UPDATE OR DELETE ON ekyc_decisions
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();

CREATE TABLE quick_auth_results (
    result_id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    profile_id BIGINT NOT NULL,
    reference_asset_id BIGINT NOT NULL REFERENCES ekyc_private_assets(asset_id),
    matched_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    command_key VARCHAR(150) NOT NULL UNIQUE,
    FOREIGN KEY(profile_id,user_id) REFERENCES ekyc_profiles(profile_id,user_id),
    CHECK (expires_at>matched_at AND expires_at<=matched_at+INTERVAL '3 months')
);
CREATE FUNCTION og_guard_quick_auth() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ekyc_profiles p JOIN ekyc_decisions d USING(profile_id)
        JOIN ekyc_private_assets a ON a.profile_id=p.profile_id
        WHERE p.profile_id=NEW.profile_id AND p.state='VERIFIED' AND d.outcome='VERIFIED'
          AND a.asset_id=NEW.reference_asset_id AND a.asset_type='REFERENCE' AND a.deleted_at IS NULL
          AND NEW.expires_at<=LEAST(a.expires_at,p.reference_expires_at)
          AND NOT EXISTS(SELECT 1 FROM ekyc_profiles pending WHERE pending.user_id=NEW.user_id
                         AND pending.state IN ('DRAFT','IN_PROGRESS','PENDING'))) THEN
        RAISE EXCEPTION 'Quick auth requires current approved private reference' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_quick_auth_guard BEFORE INSERT ON quick_auth_results
    FOR EACH ROW EXECUTE FUNCTION og_guard_quick_auth();
CREATE TRIGGER trg_quick_auth_history BEFORE UPDATE OR DELETE ON quick_auth_results
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();

ALTER TABLE addresses ADD CONSTRAINT uq_addresses_owner UNIQUE(address_id,user_id);
CREATE TABLE seller_profiles (
    seller_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(user_id),
    revision_no INTEGER NOT NULL DEFAULT 1 CHECK (revision_no>0),
    state VARCHAR(20) NOT NULL DEFAULT 'PENDING_EKYC'
        CHECK (state IN ('PENDING_EKYC','PENDING_REVIEW','APPROVED','REJECTED')),
    ekyc_profile_id BIGINT,
    quick_auth_result_id UUID REFERENCES quick_auth_results(result_id),
    pickup_address_id BIGINT,
    bank_snapshot JSONB NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(bank_snapshot)='object'),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(ekyc_profile_id,user_id) REFERENCES ekyc_profiles(profile_id,user_id),
    FOREIGN KEY(pickup_address_id,user_id) REFERENCES addresses(address_id,user_id)
);
CREATE TABLE seller_profile_decisions (
    decision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_profile_id BIGINT NOT NULL REFERENCES seller_profiles(seller_profile_id),
    revision_no INTEGER NOT NULL,
    reviewed_by BIGINT NOT NULL REFERENCES users(user_id),
    outcome VARCHAR(10) NOT NULL CHECK (outcome IN ('APPROVED','REJECTED')),
    profile_snapshot JSONB NOT NULL CHECK (jsonb_typeof(profile_snapshot)='object'),
    reason TEXT,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    command_key VARCHAR(150) NOT NULL UNIQUE,
    UNIQUE(seller_profile_id,revision_no),
    CHECK (outcome<>'REJECTED' OR NULLIF(btrim(reason),'') IS NOT NULL)
);
CREATE FUNCTION og_apply_seller_decision() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE p seller_profiles;
BEGIN
    NEW.decided_at:=clock_timestamp();
    SELECT * INTO STRICT p FROM seller_profiles WHERE seller_profile_id=NEW.seller_profile_id FOR UPDATE;
    IF p.state<>'PENDING_REVIEW' OR p.revision_no<>NEW.revision_no OR NOT og_has_role(NEW.reviewed_by,'KTV') THEN
        RAISE EXCEPTION 'Only KTV can decide current seller profile' USING ERRCODE='23514';
    END IF;
    IF NEW.outcome='APPROVED' AND (p.pickup_address_id IS NULL
        OR NOT (p.bank_snapshot ?& ARRAY['bank_name','account_number','account_holder'])
        OR NOT EXISTS(SELECT 1 FROM ekyc_profiles e JOIN ekyc_decisions d USING(profile_id)
                       WHERE e.profile_id=p.ekyc_profile_id AND e.state='VERIFIED' AND d.outcome='VERIFIED'
                         AND e.reference_expires_at>NEW.decided_at)) THEN
        RAISE EXCEPTION 'Seller prerequisites incomplete' USING ERRCODE='23514';
    END IF;
    NEW.profile_snapshot := to_jsonb(p);
    UPDATE seller_profiles SET state=NEW.outcome,updated_at=NEW.decided_at WHERE seller_profile_id=p.seller_profile_id;
    IF NEW.outcome='APPROVED' THEN
        INSERT INTO user_roles(user_id,role_id,granted_by)
            SELECT p.user_id,role_id,NEW.reviewed_by FROM roles WHERE role_name='SELLER'
            ON CONFLICT(user_id,role_id) DO NOTHING;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_seller_decision_apply BEFORE INSERT ON seller_profile_decisions
    FOR EACH ROW EXECUTE FUNCTION og_apply_seller_decision();
CREATE TRIGGER trg_seller_decisions_history BEFORE UPDATE OR DELETE ON seller_profile_decisions
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();

COMMENT ON TABLE seller_verifications IS 'Legacy V14 verification. Canonical UC83 eKYC and seller approval use separate profiles/decisions.';

-- Final states need the corresponding immutable decision in the same transaction.
CREATE FUNCTION og_validate_identity_decision() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF TG_TABLE_NAME='ekyc_profiles' THEN
        IF EXISTS(SELECT 1 FROM ekyc_profiles p WHERE p.profile_id=NEW.profile_id
            AND p.state IN ('VERIFIED','REJECTED') AND NOT EXISTS(SELECT 1 FROM ekyc_decisions d
                WHERE d.profile_id=p.profile_id AND d.outcome=p.state)) THEN
            RAISE EXCEPTION 'Final eKYC state requires KTV decision' USING ERRCODE='23514';
        END IF;
    ELSE
        IF EXISTS(SELECT 1 FROM seller_profiles p WHERE p.seller_profile_id=NEW.seller_profile_id
            AND p.state IN ('APPROVED','REJECTED') AND NOT EXISTS(SELECT 1 FROM seller_profile_decisions d
                WHERE d.seller_profile_id=p.seller_profile_id AND d.revision_no=p.revision_no AND d.outcome=p.state)) THEN
            RAISE EXCEPTION 'Final seller state requires KTV decision' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER trg_ekyc_final_proof AFTER INSERT OR UPDATE ON ekyc_profiles
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION og_validate_identity_decision();
CREATE CONSTRAINT TRIGGER trg_seller_final_proof AFTER INSERT OR UPDATE ON seller_profiles
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION og_validate_identity_decision();
CREATE FUNCTION og_guard_ekyc_snapshot() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP='DELETE' OR (TG_OP='UPDATE' AND (
        ROW(NEW.profile_id,NEW.user_id,NEW.revision_no,NEW.created_at) IS DISTINCT FROM
        ROW(OLD.profile_id,OLD.user_id,OLD.revision_no,OLD.created_at)
        OR (OLD.state IN ('PENDING','VERIFIED','REJECTED','EXPIRED') AND
            ROW(NEW.submitted_data,NEW.ai_summary,NEW.document_digest,NEW.submitted_at) IS DISTINCT FROM
            ROW(OLD.submitted_data,OLD.ai_summary,OLD.document_digest,OLD.submitted_at))
        OR (OLD.state IN ('VERIFIED','REJECTED','EXPIRED') AND NEW.state<>OLD.state
            AND NOT (OLD.state='VERIFIED' AND NEW.state='EXPIRED')))) THEN
        RAISE EXCEPTION 'eKYC identity/submitted evidence is immutable' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_ekyc_snapshot BEFORE UPDATE OR DELETE ON ekyc_profiles
    FOR EACH ROW EXECUTE FUNCTION og_guard_ekyc_snapshot();
CREATE FUNCTION og_guard_private_asset() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF TG_OP='DELETE' OR (TG_OP='UPDATE' AND ROW(NEW.profile_id,NEW.asset_type,NEW.object_key,
        NEW.content_digest,NEW.captured_at,NEW.expires_at) IS DISTINCT FROM
        ROW(OLD.profile_id,OLD.asset_type,OLD.object_key,OLD.content_digest,OLD.captured_at,OLD.expires_at)) THEN
        RAISE EXCEPTION 'Private evidence identity retained; mark deletion only' USING ERRCODE='23514';
    END IF;
    IF TG_OP='INSERT' AND NOT EXISTS(SELECT 1 FROM ekyc_profiles WHERE profile_id=NEW.profile_id
        AND state IN ('DRAFT','IN_PROGRESS')) THEN
        RAISE EXCEPTION 'Only open eKYC accepts new evidence' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_private_asset_guard BEFORE INSERT OR UPDATE OR DELETE ON ekyc_private_assets
    FOR EACH ROW EXECUTE FUNCTION og_guard_private_asset();

CREATE TABLE quick_auth_sessions (
    session_id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    reference_asset_id BIGINT NOT NULL REFERENCES ekyc_private_assets(asset_id),
    nonmatch_count INTEGER NOT NULL DEFAULT 0 CHECK(nonmatch_count BETWEEN 0 AND 15),
    last_nonmatch_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    command_key VARCHAR(150) NOT NULL UNIQUE,
    UNIQUE(session_id,user_id,profile_id,reference_asset_id),
    FOREIGN KEY(profile_id,user_id) REFERENCES ekyc_profiles(profile_id,user_id)
);
CREATE TABLE quick_auth_attempts (
    attempt_id UUID PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES quick_auth_sessions(session_id),
    result VARCHAR(15) NOT NULL CHECK(result IN ('MATCH','NON_MATCH','SERVICE_ERROR')),
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    command_key VARCHAR(150) NOT NULL UNIQUE
);
CREATE UNIQUE INDEX uq_quick_auth_match ON quick_auth_attempts(session_id) WHERE result='MATCH';
CREATE FUNCTION og_guard_quick_auth_attempt() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE s quick_auth_sessions;
BEGIN
    SELECT * INTO STRICT s FROM quick_auth_sessions WHERE session_id=NEW.session_id FOR UPDATE;
    NEW.attempted_at:=clock_timestamp();
    IF s.expires_at<=NEW.attempted_at OR s.nonmatch_count>=15 OR EXISTS(SELECT 1 FROM quick_auth_attempts
        WHERE session_id=s.session_id AND result='MATCH') OR NOT EXISTS(
        SELECT 1 FROM ekyc_profiles p JOIN ekyc_decisions d USING(profile_id)
        JOIN ekyc_private_assets a ON a.profile_id=p.profile_id WHERE p.profile_id=s.profile_id
          AND p.state='VERIFIED' AND d.outcome='VERIFIED' AND p.reference_expires_at>NEW.attempted_at
          AND a.asset_id=s.reference_asset_id AND a.asset_type='REFERENCE' AND a.deleted_at IS NULL
          AND a.expires_at>NEW.attempted_at
          AND NOT EXISTS(SELECT 1 FROM ekyc_profiles pending WHERE pending.user_id=s.user_id
              AND pending.state IN ('DRAFT','IN_PROGRESS','PENDING'))) THEN
        RAISE EXCEPTION 'Quick authentication unavailable/exhausted' USING ERRCODE='23514';
    END IF;
    IF s.last_nonmatch_at IS NOT NULL AND NEW.attempted_at<s.last_nonmatch_at+INTERVAL '3 seconds' THEN
        RAISE EXCEPTION 'Quick authentication cooldown' USING ERRCODE='23514';
    END IF;
    IF NEW.result='NON_MATCH' THEN UPDATE quick_auth_sessions SET nonmatch_count=nonmatch_count+1,
        last_nonmatch_at=NEW.attempted_at WHERE session_id=s.session_id; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_quick_attempt_guard BEFORE INSERT ON quick_auth_attempts
    FOR EACH ROW EXECUTE FUNCTION og_guard_quick_auth_attempt();
CREATE TRIGGER trg_quick_attempt_history BEFORE UPDATE OR DELETE ON quick_auth_attempts
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
ALTER TABLE quick_auth_results ADD COLUMN session_id UUID NOT NULL UNIQUE,
    ADD CONSTRAINT fk_quick_result_session FOREIGN KEY(session_id,user_id,profile_id,reference_asset_id)
        REFERENCES quick_auth_sessions(session_id,user_id,profile_id,reference_asset_id);
CREATE FUNCTION og_validate_quick_auth_match() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM quick_auth_attempts WHERE session_id=NEW.session_id AND result='MATCH'
        AND attempted_at=NEW.matched_at) OR NEW.matched_at>clock_timestamp() THEN
        RAISE EXCEPTION 'Quick authentication result requires server match' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_quick_result_match BEFORE INSERT ON quick_auth_results
    FOR EACH ROW EXECUTE FUNCTION og_validate_quick_auth_match();
CREATE FUNCTION og_validate_canonical_role() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE role_code TEXT;
BEGIN
    IF NOT EXISTS(SELECT 1 FROM users WHERE user_id=NEW.user_id AND identity_workflow='UC83') THEN RETURN NULL; END IF;
    SELECT role_name INTO role_code FROM roles WHERE role_id=NEW.role_id;
    IF (role_code='SELLER' AND NOT EXISTS(SELECT 1 FROM seller_profiles p JOIN seller_profile_decisions d USING(seller_profile_id)
        WHERE p.user_id=NEW.user_id AND p.state='APPROVED' AND p.revision_no=d.revision_no AND d.outcome='APPROVED'))
        OR (role_code IN ('KTV','ADMIN') AND NOT og_has_role(NEW.granted_by,'ADMIN')) THEN
        RAISE EXCEPTION 'Canonical role grant requires approval authority' USING ERRCODE='23514'; END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER trg_role_approval_proof AFTER INSERT OR UPDATE ON user_roles
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION og_validate_canonical_role();

CREATE FUNCTION og_consume_auth_challenge(p_challenge UUID,p_digest TEXT) RETURNS BOOLEAN
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE c auth_challenges;
BEGIN
    SELECT * INTO STRICT c FROM auth_challenges WHERE challenge_id=p_challenge FOR UPDATE;
    IF c.state<>'OPEN' OR c.expires_at<=clock_timestamp() OR c.attempt_count>=c.max_attempts THEN RETURN FALSE; END IF;
    UPDATE auth_challenges SET attempt_count=attempt_count+1,
        state=CASE WHEN code_digest=p_digest THEN 'CONSUMED' ELSE 'OPEN' END,
        consumed_at=CASE WHEN code_digest=p_digest THEN clock_timestamp() END WHERE challenge_id=c.challenge_id;
    RETURN c.code_digest=p_digest;
END;
$$;
CREATE FUNCTION og_guard_auth_challenge_history() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP='DELETE' OR ROW(NEW.challenge_id,NEW.user_id,NEW.subject_key,NEW.purpose,NEW.code_digest,
        NEW.issued_at,NEW.expires_at,NEW.next_send_at,NEW.max_attempts,NEW.command_key) IS DISTINCT FROM
        ROW(OLD.challenge_id,OLD.user_id,OLD.subject_key,OLD.purpose,OLD.code_digest,OLD.issued_at,
        OLD.expires_at,OLD.next_send_at,OLD.max_attempts,OLD.command_key)
        OR OLD.state<>'OPEN' OR NEW.attempt_count<OLD.attempt_count
        OR (NEW.state='CONSUMED' AND (NEW.attempt_count<>OLD.attempt_count+1
            OR OLD.attempt_count>=OLD.max_attempts OR clock_timestamp()>=OLD.expires_at
            OR NEW.consumed_at<OLD.issued_at OR NEW.consumed_at>=OLD.expires_at)) THEN
        RAISE EXCEPTION 'Challenge deadline/digest/consumption history retained' USING ERRCODE='23514'; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_auth_challenge_retained BEFORE UPDATE OR DELETE ON auth_challenges
    FOR EACH ROW EXECUTE FUNCTION og_guard_auth_challenge_history();
CREATE FUNCTION og_guard_seller_snapshot() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP='DELETE' OR NEW.user_id<>OLD.user_id OR NEW.revision_no<OLD.revision_no
        OR (OLD.state IN ('APPROVED','REJECTED') AND NEW.revision_no=OLD.revision_no AND
            ROW(NEW.state,NEW.ekyc_profile_id,NEW.quick_auth_result_id,NEW.pickup_address_id,NEW.bank_snapshot)
            IS DISTINCT FROM ROW(OLD.state,OLD.ekyc_profile_id,OLD.quick_auth_result_id,OLD.pickup_address_id,OLD.bank_snapshot))
        OR (NEW.revision_no>OLD.revision_no AND (NEW.revision_no<>OLD.revision_no+1 OR NEW.state NOT IN ('PENDING_EKYC','PENDING_REVIEW'))) THEN
        RAISE EXCEPTION 'Seller snapshot changes require a new review revision' USING ERRCODE='23514'; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_seller_snapshot BEFORE UPDATE OR DELETE ON seller_profiles
    FOR EACH ROW EXECUTE FUNCTION og_guard_seller_snapshot();
