-- G03/G04. New workflows are explicitly UC83; old rows are not asserted paid/approved.
DROP TRIGGER trg_check_product_media_publish ON products;
ALTER TABLE products ALTER COLUMN status TYPE VARCHAR(40);
CREATE TRIGGER trg_check_product_media_publish BEFORE UPDATE OF status ON products
    FOR EACH ROW EXECUTE FUNCTION fn_check_product_media_requirements();
ALTER TABLE products DROP CONSTRAINT ck_products_status;
ALTER TABLE products ADD CONSTRAINT ck_products_status CHECK
    (status IN ('DRAFT','PENDING','APPROVED_AWAITING_FEE','ACTIVE','RESERVED','SOLD','HIDDEN','REJECTED'));
ALTER TABLE products
    ADD COLUMN workflow_model VARCHAR(20) NOT NULL DEFAULT 'LEGACY_V14'
        CHECK (workflow_model IN ('LEGACY_V14','UC83')),
    ADD COLUMN quantity_total INTEGER NOT NULL DEFAULT 1 CHECK (quantity_total>0),
    ADD COLUMN quantity_held INTEGER NOT NULL DEFAULT 0 CHECK (quantity_held>=0),
    ADD COLUMN quantity_sold INTEGER NOT NULL DEFAULT 0 CHECK (quantity_sold>=0),
    ADD COLUMN quantity_unavailable INTEGER NOT NULL DEFAULT 0 CHECK (quantity_unavailable>=0),
    ADD COLUMN quantity_available INTEGER GENERATED ALWAYS AS
        (quantity_total-quantity_held-quantity_sold-quantity_unavailable) STORED,
    ADD COLUMN return_allowed BOOLEAN,
    ADD COLUMN delivery_options JSONB CHECK (jsonb_typeof(delivery_options)='array'),
    ADD CONSTRAINT ck_product_inventory CHECK (quantity_total>=quantity_held+quantity_sold+quantity_unavailable);
ALTER TABLE products DROP CONSTRAINT ck_products_reservation;
ALTER TABLE products ADD CONSTRAINT ck_products_reservation CHECK (
    (workflow_model='LEGACY_V14' AND (
        (status='RESERVED' AND reserved_until IS NOT NULL AND reserved_order_id IS NOT NULL)
        OR (status<>'RESERVED' AND reserved_until IS NULL AND reserved_order_id IS NULL)))
    OR (workflow_model='UC83' AND reserved_until IS NULL AND reserved_order_id IS NULL));

CREATE TABLE checklist_policies (
    checklist_policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES categories(category_id),
    policy_version INTEGER NOT NULL CHECK (policy_version>0),
    checklist JSONB NOT NULL CHECK (jsonb_typeof(checklist)='array'),
    created_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(category_id,policy_version)
);
CREATE TRIGGER trg_checklist_history BEFORE UPDATE OR DELETE ON checklist_policies
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();

CREATE TABLE product_revisions (
    revision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    revision_no BIGINT NOT NULL CHECK (revision_no>0),
    provenance VARCHAR(20) NOT NULL CHECK (provenance IN ('LEGACY_MIGRATION','UC83')),
    state VARCHAR(15) NOT NULL DEFAULT 'DRAFT' CHECK (state IN ('DRAFT','SUBMITTED','LEGACY')),
    listed_unit_price NUMERIC(19,2) NOT NULL CHECK (listed_unit_price>0),
    quantity INTEGER NOT NULL CHECK (quantity>0),
    return_allowed BOOLEAN,
    delivery_options JSONB CHECK (jsonb_typeof(delivery_options)='array'),
    content_snapshot JSONB NOT NULL CHECK (jsonb_typeof(content_snapshot)='object'),
    checklist_snapshot JSONB NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(checklist_snapshot)='array'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_at TIMESTAMPTZ,
    UNIQUE(product_id,revision_no),
    UNIQUE(revision_id,product_id),
    CHECK (provenance<>'UC83' OR (return_allowed IS NOT NULL
        AND delivery_options IS NOT NULL AND jsonb_array_length(delivery_options)>0)),
    CHECK (state<>'SUBMITTED' OR (provenance='UC83' AND submitted_at IS NOT NULL))
);
INSERT INTO product_revisions(product_id,revision_no,provenance,state,listed_unit_price,quantity,content_snapshot)
    SELECT product_id,content_revision,'LEGACY_MIGRATION','LEGACY',listed_price,1,to_jsonb(p)
    FROM products p;
COMMENT ON TABLE product_revisions IS
    'LEGACY_MIGRATION means known at upgrade, never proof of content at historical checkout.';
ALTER TABLE products ADD COLUMN current_revision_id BIGINT, ADD COLUMN public_revision_id BIGINT;
ALTER TABLE products
    ADD CONSTRAINT fk_product_current_revision FOREIGN KEY(current_revision_id,product_id)
        REFERENCES product_revisions(revision_id,product_id) DEFERRABLE INITIALLY DEFERRED,
    ADD CONSTRAINT fk_product_public_revision FOREIGN KEY(public_revision_id,product_id)
        REFERENCES product_revisions(revision_id,product_id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE revision_media (
    revision_media_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id BIGINT NOT NULL REFERENCES product_revisions(revision_id),
    media_type VARCHAR(10) NOT NULL CHECK (media_type IN ('IMAGE','VIDEO')),
    object_key TEXT NOT NULL CHECK (btrim(object_key)<>''),
    content_digest CHAR(64) CHECK (content_digest ~ '^[0-9a-f]{64}$'),
    file_size_bytes BIGINT,
    duration_seconds INTEGER,
    display_order INTEGER NOT NULL CHECK (display_order>=0),
    checklist_items JSONB NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(checklist_items)='array'),
    UNIQUE(revision_id,display_order),
    CHECK (file_size_bytes>0 AND ((media_type='IMAGE' AND file_size_bytes<=5242880)
        OR (media_type='VIDEO' AND file_size_bytes<=52428800 AND duration_seconds BETWEEN 1 AND 60))),
    CHECK (content_digest IS NOT NULL AND file_size_bytes IS NOT NULL),
    CHECK (media_type<>'VIDEO' OR duration_seconds IS NOT NULL)
);
CREATE FUNCTION og_guard_revision_media() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE parent product_revisions; n INTEGER;
BEGIN
    IF TG_OP<>'INSERT' THEN
        SELECT * INTO STRICT parent FROM product_revisions WHERE revision_id=OLD.revision_id FOR UPDATE;
        IF parent.state<>'DRAFT' THEN
            RAISE EXCEPTION 'Submitted revision media is immutable' USING ERRCODE='23514';
        END IF;
        IF TG_OP='DELETE' THEN RETURN OLD; END IF;
        IF NEW.revision_id<>OLD.revision_id THEN
            RAISE EXCEPTION 'Cannot move media between revisions' USING ERRCODE='23514';
        END IF;
    ELSE
        SELECT * INTO STRICT parent FROM product_revisions WHERE revision_id=NEW.revision_id FOR UPDATE;
    END IF;
    IF parent.state<>'DRAFT' OR parent.provenance<>'UC83' THEN
        RAISE EXCEPTION 'Only current draft accepts media' USING ERRCODE='23514';
    END IF;
    SELECT count(*) INTO n FROM revision_media WHERE revision_id=NEW.revision_id
        AND media_type=NEW.media_type AND revision_media_id IS DISTINCT FROM NEW.revision_media_id;
    IF n >= (CASE NEW.media_type WHEN 'IMAGE' THEN 5 ELSE 2 END) THEN
        RAISE EXCEPTION 'Revision media count exceeded' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_revision_media_guard BEFORE INSERT OR UPDATE OR DELETE ON revision_media
    FOR EACH ROW EXECUTE FUNCTION og_guard_revision_media();

CREATE FUNCTION og_guard_product_revision() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF TG_OP='INSERT' THEN
        IF NEW.provenance='UC83' AND NEW.state<>'DRAFT' THEN
            RAISE EXCEPTION 'UC83 revision starts as draft' USING ERRCODE='23514';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP='DELETE' OR OLD.state<>'DRAFT' THEN
        RAISE EXCEPTION 'Product revision history is immutable' USING ERRCODE='23514';
    END IF;
    IF NEW.state='SUBMITTED' AND (
        (SELECT count(*) FROM revision_media WHERE revision_id=NEW.revision_id AND media_type='IMAGE') NOT BETWEEN 1 AND 5
        OR (SELECT count(*) FROM revision_media WHERE revision_id=NEW.revision_id AND media_type='VIDEO') NOT BETWEEN 1 AND 2) THEN
        RAISE EXCEPTION 'Submission requires images and videos' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_product_revision_guard BEFORE INSERT OR UPDATE OR DELETE ON product_revisions
    FOR EACH ROW EXECUTE FUNCTION og_guard_product_revision();

CREATE TABLE media_analysis_runs (
    analysis_id UUID PRIMARY KEY,
    revision_id BIGINT NOT NULL REFERENCES product_revisions(revision_id),
    input_digest CHAR(64) NOT NULL CHECK (input_digest ~ '^[0-9a-f]{64}$'),
    processing_state VARCHAR(20) NOT NULL CHECK (processing_state IN ('PENDING','PROCESSING','COMPLETED','ERROR','NOT_RUN')),
    conclusion VARCHAR(20) CHECK (conclusion IN ('PASS','FAIL','INCONCLUSIVE')),
    model_metadata JSONB NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(model_metadata)='object'),
    file_results JSONB NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(file_results)='array'),
    frame_policy JSONB NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(frame_policy)='object'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    command_key VARCHAR(150) NOT NULL UNIQUE,
    CHECK ((processing_state='COMPLETED' AND conclusion IS NOT NULL AND completed_at IS NOT NULL)
        OR (processing_state<>'COMPLETED' AND conclusion IS NULL))
);

ALTER TABLE product_moderation_decisions ADD COLUMN revision_id BIGINT,
    ADD CONSTRAINT uq_moderation_decision_product UNIQUE(decision_id,product_id),
    ADD CONSTRAINT fk_moderation_revision FOREIGN KEY(revision_id,product_id)
        REFERENCES product_revisions(revision_id,product_id);
CREATE UNIQUE INDEX uq_moderation_final_revision ON product_moderation_decisions(revision_id)
    WHERE revision_id IS NOT NULL;
CREATE FUNCTION og_guard_canonical_moderation() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF NEW.revision_id IS NOT NULL AND (
        NOT og_has_role(NEW.reviewer_id,'KTV') OR NOT EXISTS (
            SELECT 1 FROM product_revisions r JOIN products p USING(product_id)
            WHERE r.revision_id=NEW.revision_id AND r.state='SUBMITTED' AND r.provenance='UC83'
              AND p.current_revision_id=r.revision_id AND p.status='PENDING')) THEN
        RAISE EXCEPTION 'KTV must review the current submitted revision' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_canonical_moderation_guard BEFORE INSERT ON product_moderation_decisions
    FOR EACH ROW EXECUTE FUNCTION og_guard_canonical_moderation();

-- Forward fix of V6 guards, retaining incomplete legacy metadata.
DROP TRIGGER trg_check_product_media_limits ON product_media;
CREATE OR REPLACE FUNCTION fn_enforce_product_media_limits() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE n INTEGER;
BEGIN
    IF TG_OP='UPDATE' AND NEW.product_id<>OLD.product_id THEN
        RAISE EXCEPTION 'Cannot move media between products' USING ERRCODE='23514';
    END IF;
    PERFORM 1 FROM products WHERE product_id=NEW.product_id FOR UPDATE;
    SELECT count(*) INTO n FROM product_media WHERE product_id=NEW.product_id
        AND media_type=NEW.media_type AND media_id IS DISTINCT FROM NEW.media_id;
    IF n >= (CASE NEW.media_type WHEN 'IMAGE' THEN 5 ELSE 2 END) THEN
        RAISE EXCEPTION 'Product media limit exceeded' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_check_product_media_limits BEFORE INSERT OR UPDATE ON product_media
    FOR EACH ROW EXECUTE FUNCTION fn_enforce_product_media_limits();
ALTER TABLE product_media ADD CONSTRAINT ck_product_media_image_size
    CHECK (media_type<>'IMAGE' OR file_size_bytes IS NULL OR file_size_bytes<=5242880) NOT VALID;

CREATE TABLE listing_fee_policies (
    policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_code VARCHAR(60) NOT NULL UNIQUE,
    threshold_amount NUMERIC(19,2) NOT NULL CHECK (threshold_amount>0),
    fixed_below NUMERIC(19,2) NOT NULL CHECK (fixed_below>=0),
    rate_at_or_above NUMERIC(8,6) NOT NULL CHECK (rate_at_or_above BETWEEN 0 AND 1),
    effective_from TIMESTAMPTZ NOT NULL,
    effective_until TIMESTAMPTZ,
    created_by BIGINT REFERENCES users(user_id),
    CHECK (effective_until IS NULL OR effective_until>effective_from),
    EXCLUDE USING gist (tstzrange(effective_from,effective_until,'[)') WITH &&)
);
INSERT INTO listing_fee_policies(policy_code,threshold_amount,fixed_below,rate_at_or_above,effective_from)
    VALUES('LISTING_INITIAL_V1',100000,10000,0.10,CURRENT_TIMESTAMP);

CREATE TABLE listing_fee_assessments (
    assessment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    revision_id BIGINT NOT NULL UNIQUE,
    decision_id BIGINT NOT NULL UNIQUE,
    policy_id BIGINT NOT NULL REFERENCES listing_fee_policies(policy_id),
    listed_total NUMERIC(19,2) NOT NULL CHECK (listed_total>0),
    previous_approved_total NUMERIC(19,2),
    computed_fee NUMERIC(19,2) NOT NULL CHECK (computed_fee>=0),
    cumulative_before NUMERIC(19,2) NOT NULL CHECK (cumulative_before>=0),
    amount_due NUMERIC(19,2) NOT NULL CHECK (amount_due>=0),
    assessed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    command_key VARCHAR(150) NOT NULL UNIQUE,
    FOREIGN KEY(revision_id,product_id) REFERENCES product_revisions(revision_id,product_id),
    FOREIGN KEY(decision_id,product_id) REFERENCES product_moderation_decisions(decision_id,product_id)
);
CREATE TABLE listing_fee_charges (
    charge_id UUID PRIMARY KEY,
    assessment_id BIGINT NOT NULL UNIQUE REFERENCES listing_fee_assessments(assessment_id),
    amount NUMERIC(19,2) NOT NULL CHECK (amount>0),
    state VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (state IN ('PENDING','CONFIRMED','CANCELLED','RECONCILIATION')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    command_key VARCHAR(150) NOT NULL UNIQUE
);
CREATE TABLE listing_fee_receipts (
    receipt_id UUID PRIMARY KEY,
    charge_id UUID NOT NULL UNIQUE REFERENCES listing_fee_charges(charge_id),
    provider VARCHAR(30) NOT NULL,
    provider_transaction_id VARCHAR(150) NOT NULL,
    amount NUMERIC(19,2) NOT NULL CHECK (amount>0),
    confirmed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(provider,provider_transaction_id)
);
CREATE FUNCTION og_compute_listing_assessment() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE r product_revisions; f listing_fee_policies;
BEGIN
    PERFORM 1 FROM products WHERE product_id=NEW.product_id FOR UPDATE;
    SELECT * INTO STRICT r FROM product_revisions WHERE revision_id=NEW.revision_id;
    IF r.state<>'SUBMITTED' OR r.provenance<>'UC83' OR NOT EXISTS (
        SELECT 1 FROM product_moderation_decisions WHERE decision_id=NEW.decision_id
            AND revision_id=r.revision_id AND decision='APPROVED') THEN
        RAISE EXCEPTION 'Fee requires approval of this revision' USING ERRCODE='23514';
    END IF;
    IF EXISTS(SELECT 1 FROM listing_fee_charges c JOIN listing_fee_assessments a USING(assessment_id)
              WHERE a.product_id=NEW.product_id AND c.state IN ('PENDING','RECONCILIATION')) THEN
        RAISE EXCEPTION 'Listing has an unresolved fee charge' USING ERRCODE='23514';
    END IF;
    NEW.assessed_at := clock_timestamp();
    SELECT * INTO STRICT f FROM listing_fee_policies WHERE policy_id=NEW.policy_id
        AND effective_from<=NEW.assessed_at AND (effective_until IS NULL OR effective_until>NEW.assessed_at);
    NEW.listed_total := r.listed_unit_price*r.quantity;
    SELECT listed_total INTO NEW.previous_approved_total FROM listing_fee_assessments
        WHERE product_id=NEW.product_id ORDER BY assessment_id DESC LIMIT 1;
    SELECT COALESCE(sum(receipt.amount),0) INTO NEW.cumulative_before FROM listing_fee_receipts receipt
        JOIN listing_fee_charges c USING(charge_id) JOIN listing_fee_assessments a USING(assessment_id)
        WHERE a.product_id=NEW.product_id;
    NEW.computed_fee := CASE WHEN NEW.listed_total<f.threshold_amount THEN f.fixed_below
        ELSE round(NEW.listed_total*f.rate_at_or_above,0) END;
    NEW.amount_due := CASE WHEN NEW.previous_approved_total IS NULL
        OR NEW.listed_total>NEW.previous_approved_total
        THEN greatest(0,NEW.computed_fee-NEW.cumulative_before) ELSE 0 END;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_listing_assessment_compute BEFORE INSERT ON listing_fee_assessments
    FOR EACH ROW EXECUTE FUNCTION og_compute_listing_assessment();
CREATE TRIGGER trg_listing_assessment_history BEFORE UPDATE OR DELETE ON listing_fee_assessments
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
CREATE FUNCTION og_guard_listing_charge() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM listing_fee_assessments WHERE assessment_id=NEW.assessment_id
        AND amount_due=NEW.amount AND amount_due>0) THEN
        RAISE EXCEPTION 'Listing fee charge must equal positive assessment due' USING ERRCODE='23514';
    END IF;
    IF TG_OP='UPDATE' AND (NEW.assessment_id<>OLD.assessment_id OR NEW.amount<>OLD.amount
        OR (OLD.state='CONFIRMED' AND NEW IS DISTINCT FROM OLD)) THEN
        RAISE EXCEPTION 'Confirmed listing charge is immutable' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_listing_charge_guard BEFORE INSERT OR UPDATE ON listing_fee_charges
    FOR EACH ROW EXECUTE FUNCTION og_guard_listing_charge();
CREATE FUNCTION og_confirm_listing_receipt() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE c listing_fee_charges; p BIGINT;
BEGIN
    SELECT product_id INTO STRICT p FROM listing_fee_assessments a JOIN listing_fee_charges ch USING(assessment_id)
        WHERE ch.charge_id=NEW.charge_id;
    PERFORM 1 FROM products WHERE product_id=p FOR UPDATE;
    SELECT * INTO STRICT c FROM listing_fee_charges WHERE charge_id=NEW.charge_id FOR UPDATE;
    IF c.state<>'PENDING' OR NEW.amount<>c.amount THEN
        RAISE EXCEPTION 'Listing fee amount/state mismatch; reconciliation required' USING ERRCODE='23514';
    END IF;
    UPDATE listing_fee_charges SET state='CONFIRMED' WHERE charge_id=NEW.charge_id;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_listing_receipt_confirm BEFORE INSERT ON listing_fee_receipts
    FOR EACH ROW EXECUTE FUNCTION og_confirm_listing_receipt();
CREATE TRIGGER trg_listing_receipt_history BEFORE UPDATE OR DELETE ON listing_fee_receipts
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
CREATE VIEW listing_fee_totals AS
    SELECT a.product_id,sum(r.amount) AS cumulative_confirmed_fee
    FROM listing_fee_receipts r JOIN listing_fee_charges c USING(charge_id)
        JOIN listing_fee_assessments a USING(assessment_id) GROUP BY a.product_id;

CREATE FUNCTION og_guard_listing_activation() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF NEW.workflow_model='UC83' AND NEW.status='ACTIVE' THEN
        IF NEW.current_revision_id IS DISTINCT FROM NEW.public_revision_id OR NOT EXISTS (
            SELECT 1 FROM product_revisions r JOIN listing_fee_assessments a USING(revision_id)
            WHERE r.revision_id=NEW.public_revision_id AND r.product_id=NEW.product_id AND r.provenance='UC83'
              AND r.listed_unit_price=NEW.listed_price AND r.quantity=NEW.quantity_total
              AND r.return_allowed IS NOT DISTINCT FROM NEW.return_allowed
              AND r.delivery_options=NEW.delivery_options
              AND (a.amount_due=0 OR EXISTS(SELECT 1 FROM listing_fee_receipts receipt
                  JOIN listing_fee_charges c USING(charge_id) WHERE c.assessment_id=a.assessment_id))
        ) OR NOT EXISTS(SELECT 1 FROM seller_profiles s JOIN seller_profile_decisions d USING(seller_profile_id)
            WHERE s.user_id=NEW.seller_id AND s.state='APPROVED' AND d.revision_no=s.revision_no
              AND d.outcome='APPROVED') OR NOT og_has_role(NEW.seller_id,'SELLER') THEN
            RAISE EXCEPTION 'ACTIVE requires current KTV approval, confirmed listing fee and seller approval'
                USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_listing_activation_guard BEFORE INSERT OR UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION og_guard_listing_activation();

-- UC83 publish validates revision_media; the V6 projection still protects legacy writers.
DROP TRIGGER trg_check_product_media_publish ON products;
CREATE TRIGGER trg_check_product_media_publish BEFORE UPDATE OF status ON products
    FOR EACH ROW WHEN (NEW.workflow_model='LEGACY_V14')
    EXECUTE FUNCTION fn_check_product_media_requirements();
CREATE FUNCTION og_validate_listing_decision_fee() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF NEW.revision_id IS NOT NULL AND NEW.decision='APPROVED' AND NOT EXISTS(
        SELECT 1 FROM listing_fee_assessments WHERE decision_id=NEW.decision_id) THEN
        RAISE EXCEPTION 'Approval must assess listing fee in the same transaction' USING ERRCODE='23514';
    END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER trg_approval_fee_proof AFTER INSERT ON product_moderation_decisions
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION og_validate_listing_decision_fee();
CREATE FUNCTION og_validate_listing_receipt() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF EXISTS(SELECT 1 FROM listing_fee_charges c WHERE c.charge_id=NEW.charge_id AND c.state='CONFIRMED'
        AND NOT EXISTS(SELECT 1 FROM listing_fee_receipts r WHERE r.charge_id=c.charge_id AND r.amount=c.amount)) THEN
        RAISE EXCEPTION 'Confirmed charge requires exact receipt' USING ERRCODE='23514';
    END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER trg_listing_charge_proof AFTER INSERT OR UPDATE ON listing_fee_charges
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION og_validate_listing_receipt();
CREATE TRIGGER trg_listing_charge_retained BEFORE DELETE ON listing_fee_charges
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
CREATE FUNCTION og_guard_fee_policy() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF TG_OP='DELETE' OR ROW(NEW.policy_code,NEW.threshold_amount,NEW.fixed_below,NEW.rate_at_or_above,
        NEW.effective_from,NEW.created_by) IS DISTINCT FROM ROW(OLD.policy_code,OLD.threshold_amount,
        OLD.fixed_below,OLD.rate_at_or_above,OLD.effective_from,OLD.created_by)
        OR NEW.effective_until IS NULL OR NEW.effective_until<=clock_timestamp()
        OR EXISTS(SELECT 1 FROM listing_fee_assessments WHERE policy_id=OLD.policy_id AND assessed_at>=NEW.effective_until) THEN
        RAISE EXCEPTION 'Keep fee policy history; end policy in the future and create a successor' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_fee_policy_history BEFORE UPDATE OR DELETE ON listing_fee_policies
    FOR EACH ROW EXECUTE FUNCTION og_guard_fee_policy();

-- Run data backfill after DDL: existing SOLD rows queue V8 deferred membership triggers.
-- Altering products again before those events finish would fail on populated upgrades.
UPDATE products SET quantity_sold=1 WHERE status='SOLD';
