-- G08/G09. One case owns multiple rounds; shipping directions retain separate identities.
CREATE TABLE cases (
    case_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_type VARCHAR(20) NOT NULL CHECK(case_type IN ('RETURN','SYSTEM_ISSUE')),
    order_id BIGINT REFERENCES orders(order_id),
    product_id BIGINT REFERENCES products(product_id),
    listing_charge_id UUID REFERENCES listing_fee_charges(charge_id),
    payment_intent_id UUID REFERENCES payment_intents(intent_id),
    target_user_id BIGINT REFERENCES users(user_id),
    created_by BIGINT NOT NULL REFERENCES users(user_id),
    assigned_to BIGINT REFERENCES users(user_id),
    description TEXT NOT NULL CHECK(btrim(description)<>''),
    state VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK(state IN ('OPEN','REVIEWING','RETURN_APPROVED','RETURNING','POST_RETURN','CLOSED','REJECTED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMPTZ,
    valid_returned_at TIMESTAMPTZ,
    seller_response_due_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    last_related_completion_at TIMESTAMPTZ,
    command_key VARCHAR(150) NOT NULL UNIQUE,
    CHECK((order_id IS NOT NULL)::INTEGER+(product_id IS NOT NULL)::INTEGER+
        (listing_charge_id IS NOT NULL)::INTEGER+(payment_intent_id IS NOT NULL)::INTEGER+
        (target_user_id IS NOT NULL)::INTEGER=1),
    CHECK(case_type<>'RETURN' OR order_id IS NOT NULL),
    CHECK(valid_returned_at IS NULL OR (approved_at IS NOT NULL AND valid_returned_at>=approved_at
        AND seller_response_due_at=valid_returned_at+INTERVAL '2 days')),
    CHECK(state NOT IN ('CLOSED','REJECTED') OR closed_at IS NOT NULL)
);
CREATE UNIQUE INDEX uq_return_case_active ON cases(order_id)
    WHERE case_type='RETURN' AND state NOT IN ('CLOSED','REJECTED');
CREATE INDEX ix_case_work_queue ON cases(assigned_to,state,created_at,case_id);
CREATE FUNCTION og_guard_return_case() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE o orders;
BEGIN
    IF NEW.state<>'OPEN' THEN RAISE EXCEPTION 'New case starts open' USING ERRCODE='23514'; END IF;
    IF NEW.case_type='RETURN' AND TG_OP='INSERT' THEN
        SELECT * INTO STRICT o FROM orders WHERE order_id=NEW.order_id FOR UPDATE;
        NEW.created_at:=clock_timestamp();
        IF o.workflow_model<>'UC83' OR NEW.created_by<>o.buyer_id OR NOT o.return_allowed
            OR o.valid_delivered_at IS NULL OR o.early_completed_at IS NOT NULL
            OR NEW.created_at>o.valid_delivered_at+INTERVAL '3 days' THEN
            RAISE EXCEPTION 'Order has no current right to request return' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_return_case_guard BEFORE INSERT ON cases FOR EACH ROW EXECUTE FUNCTION og_guard_return_case();

CREATE TABLE case_rounds (
    round_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES cases(case_id),
    round_no INTEGER NOT NULL CHECK(round_no>0),
    stage VARCHAR(25) NOT NULL CHECK(stage IN ('RETURN_APPROVAL','POST_RETURN_RESOLUTION','SYSTEM_REVIEW')),
    state VARCHAR(15) NOT NULL DEFAULT 'OPEN' CHECK(state IN ('OPEN','DECIDED')),
    opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    complete_submission_at TIMESTAMPTZ,
    ktv_due_at TIMESTAMPTZ,
    valid_damage_request_at TIMESTAMPTZ,
    UNIQUE(case_id,round_no),
    UNIQUE(round_id,case_id),
    CHECK(ktv_due_at IS NULL OR (complete_submission_at IS NOT NULL
        AND ktv_due_at=complete_submission_at+INTERVAL '48 hours'))
);
CREATE UNIQUE INDEX uq_case_stage_round ON case_rounds(case_id,stage) WHERE stage IN ('RETURN_APPROVAL','POST_RETURN_RESOLUTION');
CREATE TABLE case_decisions (
    decision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL REFERENCES case_rounds(round_id),
    reviewed_by BIGINT REFERENCES users(user_id),
    actor_type VARCHAR(20) NOT NULL DEFAULT 'USER' CHECK(actor_type IN ('USER','SYSTEM_TIMEOUT')),
    outcome VARCHAR(25) NOT NULL CHECK(outcome IN
        ('APPROVE_RETURN','REJECT_RETURN','SELLER_DECLINED','FULL_GOODS_REFUND','EXEMPT_GOODS_REFUND','SYSTEM_RESOLVED')),
    is_final BOOLEAN NOT NULL DEFAULT TRUE,
    goods_refund_amount NUMERIC(19,2),
    reason TEXT NOT NULL CHECK(btrim(reason)<>''),
    decided_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    supersedes_decision_id BIGINT REFERENCES case_decisions(decision_id),
    command_key VARCHAR(150) NOT NULL UNIQUE,
    CHECK((actor_type='USER' AND reviewed_by IS NOT NULL) OR (actor_type='SYSTEM_TIMEOUT' AND reviewed_by IS NULL)),
    CHECK(goods_refund_amount IS NULL OR goods_refund_amount>=0),
    CHECK((outcome='SELLER_DECLINED' AND NOT is_final) OR outcome<>'SELLER_DECLINED')
);
CREATE UNIQUE INDEX uq_case_round_final ON case_decisions(round_id) WHERE is_final AND supersedes_decision_id IS NULL;
CREATE FUNCTION og_apply_case_decision() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE r case_rounds; c cases; o orders;
BEGIN
    NEW.decided_at:=clock_timestamp();
    IF NEW.supersedes_decision_id IS NOT NULL OR (NEW.outcome<>'SELLER_DECLINED' AND NOT NEW.is_final) THEN
        RAISE EXCEPTION 'Final decisions retained; reopening needs a separate authorized round' USING ERRCODE='23514';
    END IF;
    SELECT * INTO STRICT r FROM case_rounds WHERE round_id=NEW.round_id FOR UPDATE;
    SELECT * INTO STRICT c FROM cases WHERE case_id=r.case_id FOR UPDATE;
    IF r.state<>'OPEN' AND NEW.supersedes_decision_id IS NULL THEN
        RAISE EXCEPTION 'Case round already decided' USING ERRCODE='23514';
    END IF;
    IF c.order_id IS NOT NULL THEN SELECT * INTO STRICT o FROM orders WHERE order_id=c.order_id FOR UPDATE; END IF;
    IF r.stage='RETURN_APPROVAL' THEN
        IF NEW.actor_type<>'USER' OR NEW.outcome NOT IN ('APPROVE_RETURN','REJECT_RETURN','SELLER_DECLINED')
            OR NOT (og_has_role(NEW.reviewed_by,'KTV') OR
                (NEW.reviewed_by=o.seller_id AND NEW.outcome IN ('APPROVE_RETURN','SELLER_DECLINED'))) THEN
            RAISE EXCEPTION 'Return approval authority/outcome mismatch' USING ERRCODE='23514';
        END IF;
        IF NEW.outcome='APPROVE_RETURN' THEN
            UPDATE cases SET state='RETURN_APPROVED',approved_at=NEW.decided_at WHERE case_id=c.case_id;
        ELSIF NEW.outcome='REJECT_RETURN' THEN
            UPDATE cases SET state='REJECTED',closed_at=NEW.decided_at WHERE case_id=c.case_id;
        END IF;
    ELSIF r.stage='POST_RETURN_RESOLUTION' THEN
        IF c.valid_returned_at IS NULL OR NEW.outcome NOT IN ('FULL_GOODS_REFUND','EXEMPT_GOODS_REFUND') THEN
            RAISE EXCEPTION 'Post-return decision needs valid returned delivery' USING ERRCODE='23514';
        END IF;
        IF NEW.outcome='EXEMPT_GOODS_REFUND' AND (NEW.actor_type<>'USER' OR NOT og_has_role(NEW.reviewed_by,'KTV')
            OR r.valid_damage_request_at IS NULL) THEN
            RAISE EXCEPTION 'Only KTV may grant exemption after valid request' USING ERRCODE='23514';
        END IF;
        IF NEW.actor_type='SYSTEM_TIMEOUT' AND (NEW.outcome<>'FULL_GOODS_REFUND'
            OR NEW.decided_at<c.seller_response_due_at OR r.valid_damage_request_at IS NOT NULL) THEN
            RAISE EXCEPTION 'Auto refund blocked by deadline/request' USING ERRCODE='23514';
        END IF;
        IF NEW.actor_type='USER' AND NOT (og_has_role(NEW.reviewed_by,'KTV')
            OR (NEW.reviewed_by=o.seller_id AND NEW.outcome='FULL_GOODS_REFUND')) THEN
            RAISE EXCEPTION 'Post-return decision authority mismatch' USING ERRCODE='23514';
        END IF;
        NEW.goods_refund_amount:=CASE WHEN NEW.outcome='FULL_GOODS_REFUND'
            THEN o.subtotal-o.voucher_discount_amount-o.points_discount_amount ELSE 0 END;
        UPDATE cases SET state='CLOSED',closed_at=NEW.decided_at WHERE case_id=c.case_id;
    ELSE
        IF NEW.outcome<>'SYSTEM_RESOLVED' OR NEW.actor_type<>'USER' OR
            NOT (og_has_role(NEW.reviewed_by,'KTV') OR og_has_role(NEW.reviewed_by,'ADMIN')) THEN
            RAISE EXCEPTION 'System issue authority mismatch' USING ERRCODE='23514';
        END IF;
        UPDATE cases SET state='CLOSED',closed_at=NEW.decided_at WHERE case_id=c.case_id;
    END IF;
    IF NEW.is_final THEN UPDATE case_rounds SET state='DECIDED' WHERE round_id=r.round_id; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_case_decision_apply BEFORE INSERT ON case_decisions
    FOR EACH ROW EXECUTE FUNCTION og_apply_case_decision();
CREATE TRIGGER trg_case_decision_history BEFORE UPDATE OR DELETE ON case_decisions
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();

CREATE TABLE case_evidence (
    evidence_id UUID PRIMARY KEY,
    round_id BIGINT NOT NULL REFERENCES case_rounds(round_id),
    submitted_by BIGINT NOT NULL REFERENCES users(user_id),
    submission_no INTEGER NOT NULL CHECK(submission_no>0),
    media_type VARCHAR(10) NOT NULL CHECK(media_type IN ('IMAGE','VIDEO','TEXT')),
    object_key TEXT,
    text_content TEXT,
    content_digest CHAR(64),
    file_size_bytes BIGINT,
    duration_seconds INTEGER,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CHECK((media_type='TEXT' AND NULLIF(btrim(text_content),'') IS NOT NULL AND object_key IS NULL)
       OR (media_type IN ('IMAGE','VIDEO') AND NULLIF(btrim(object_key),'') IS NOT NULL
         AND content_digest IS NOT NULL AND content_digest ~ '^[0-9a-f]{64}$' AND file_size_bytes IS NOT NULL AND file_size_bytes>0
         AND ((media_type='IMAGE' AND file_size_bytes<=5242880)
           OR (media_type='VIDEO' AND file_size_bytes<=52428800 AND duration_seconds IS NOT NULL AND duration_seconds BETWEEN 1 AND 60))))
);
CREATE FUNCTION og_guard_case_evidence() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE r case_rounds; c cases; o orders; n INTEGER;
BEGIN
    SELECT * INTO STRICT r FROM case_rounds WHERE round_id=NEW.round_id FOR UPDATE;
    SELECT * INTO STRICT c FROM cases WHERE case_id=r.case_id;
    IF r.state<>'OPEN' THEN RAISE EXCEPTION 'Evidence round closed' USING ERRCODE='23514'; END IF;
    NEW.submitted_at:=clock_timestamp();
    IF c.order_id IS NOT NULL THEN
        SELECT * INTO STRICT o FROM orders WHERE order_id=c.order_id;
        IF NEW.submitted_by NOT IN (o.buyer_id,o.seller_id) AND NOT og_has_role(NEW.submitted_by,'KTV') THEN
            RAISE EXCEPTION 'Evidence author not a party/KTV' USING ERRCODE='23514';
        END IF;
        IF NEW.submitted_by=o.buyer_id AND c.case_type='RETURN'
            AND NEW.submitted_at>o.valid_delivered_at+INTERVAL '3 days' THEN
            RAISE EXCEPTION 'Buyer evidence submission deadline passed' USING ERRCODE='23514';
        END IF;
    ELSIF NEW.submitted_by<>c.created_by AND NOT og_has_role(NEW.submitted_by,'KTV') THEN
        RAISE EXCEPTION 'Private system issue evidence author invalid' USING ERRCODE='23514';
    END IF;
    SELECT count(*) INTO n FROM case_evidence WHERE round_id=NEW.round_id
        AND submitted_by=NEW.submitted_by AND submission_no=NEW.submission_no AND media_type=NEW.media_type;
    IF (NEW.media_type='IMAGE' AND n>=5) OR (NEW.media_type='VIDEO' AND n>=2) THEN
        RAISE EXCEPTION 'Evidence submission media limit exceeded' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_case_evidence_guard BEFORE INSERT ON case_evidence
    FOR EACH ROW EXECUTE FUNCTION og_guard_case_evidence();
CREATE TRIGGER trg_case_evidence_history BEFORE UPDATE OR DELETE ON case_evidence
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
CREATE TABLE case_events (
    event_id UUID PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES cases(case_id),
    round_id BIGINT,
    actor_id BIGINT REFERENCES users(user_id),
    recipient_id BIGINT REFERENCES users(user_id),
    event_type VARCHAR(30) NOT NULL CHECK(event_type IN
        ('SUBMITTED','SUPPLEMENTED','VALID_DAMAGE_REQUEST','ESCALATED','ASSIGNED','COMPENSATION','DEADLINE_EXTENSION','CLEANUP')),
    reason TEXT NOT NULL CHECK(btrim(reason)<>''),
    metadata JSONB NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(metadata)='object'),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    command_key VARCHAR(150) NOT NULL UNIQUE,
    FOREIGN KEY(round_id,case_id) REFERENCES case_rounds(round_id,case_id)
);
CREATE FUNCTION og_guard_case_event() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE c cases; o orders;
BEGIN
    SELECT * INTO STRICT c FROM cases WHERE case_id=NEW.case_id FOR UPDATE;
    NEW.occurred_at:=clock_timestamp();
    IF NEW.event_type='ESCALATED' AND (NOT og_has_role(NEW.actor_id,'KTV') OR
        NOT og_has_role(NEW.recipient_id,'ADMIN')) THEN
        RAISE EXCEPTION 'Escalation needs KTV to Admin' USING ERRCODE='23514';
    END IF;
    IF NEW.event_type='VALID_DAMAGE_REQUEST' THEN
        SELECT * INTO STRICT o FROM orders WHERE order_id=c.order_id;
        IF NEW.actor_id<>o.seller_id OR c.valid_returned_at IS NULL OR NEW.occurred_at>c.seller_response_due_at
            OR NOT EXISTS(SELECT 1 FROM case_rounds WHERE round_id=NEW.round_id
                AND stage='POST_RETURN_RESOLUTION' AND state='OPEN')
            OR NOT EXISTS(SELECT 1 FROM case_evidence WHERE round_id=NEW.round_id AND submitted_by=NEW.actor_id) THEN
            RAISE EXCEPTION 'Only complete in-time Seller request blocks auto refund' USING ERRCODE='23514';
        END IF;
        UPDATE case_rounds SET valid_damage_request_at=NEW.occurred_at WHERE round_id=NEW.round_id;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_case_event_guard BEFORE INSERT ON case_events FOR EACH ROW EXECUTE FUNCTION og_guard_case_event();
CREATE TRIGGER trg_case_event_history BEFORE UPDATE OR DELETE ON case_events
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
ALTER TABLE settlement_operations ADD CONSTRAINT fk_settlement_case_decision
    FOREIGN KEY(case_decision_id) REFERENCES case_decisions(decision_id);
CREATE OR REPLACE FUNCTION og_case_settlement_allowed(p_decision BIGINT,p_order BIGINT,p_cause TEXT) RETURNS BOOLEAN
LANGUAGE sql STABLE SET search_path FROM CURRENT AS $$
    SELECT EXISTS(SELECT 1 FROM case_decisions d JOIN case_rounds r USING(round_id) JOIN cases c USING(case_id)
        WHERE d.decision_id=p_decision AND c.order_id=p_order AND c.case_type='RETURN'
          AND c.valid_returned_at IS NOT NULL AND d.is_final
          AND ((p_cause='RETURN' AND d.outcome='FULL_GOODS_REFUND')
            OR (p_cause='EXEMPTION' AND d.outcome='EXEMPT_GOODS_REFUND')))
$$;
CREATE OR REPLACE FUNCTION og_order_has_blocking_case(p_order BIGINT) RETURNS BOOLEAN
LANGUAGE sql STABLE SET search_path FROM CURRENT AS $$
    SELECT EXISTS(SELECT 1 FROM cases WHERE order_id=p_order AND state NOT IN ('CLOSED','REJECTED'))
$$;
ALTER TABLE money_holds ADD COLUMN case_id BIGINT REFERENCES cases(case_id);
CREATE FUNCTION og_return_case_money_holds() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF NEW.case_type='RETURN' THEN
        INSERT INTO money_holds(hold_id,component_id,source_key,reason,case_id)
            SELECT gen_random_uuid(),component_id,'RETURN_CASE:'||NEW.case_id,'Return case pending',NEW.case_id
            FROM order_fund_components WHERE order_id=NEW.order_id
                AND component_type IN ('GOODS_CASH','PLATFORM_GOODS_SUBSIDY')
            ON CONFLICT(component_id,source_key) DO NOTHING;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_return_case_holds AFTER INSERT ON cases
    FOR EACH ROW EXECUTE FUNCTION og_return_case_money_holds();

ALTER TABLE shipments DROP CONSTRAINT shipments_order_id_key;
ALTER TABLE shipments
    ADD COLUMN leg VARCHAR(15) NOT NULL DEFAULT 'OUTBOUND' CHECK(leg IN ('OUTBOUND','RETURN','RECALL')),
    ADD COLUMN workflow_model VARCHAR(20) NOT NULL DEFAULT 'LEGACY_V14'
        CHECK(workflow_model IN ('LEGACY_V14','UC83')),
    ADD COLUMN return_case_id BIGINT REFERENCES cases(case_id),
    ADD COLUMN delivery_method VARCHAR(20) CHECK(delivery_method IN ('CARRIER','SELF_PICKUP','SELF_DELIVERY')),
    ADD COLUMN fee_snapshot NUMERIC(19,2) CHECK(fee_snapshot>=0),
    ADD COLUMN fee_payer VARCHAR(10) CHECK(fee_payer IN ('BUYER','SELLER','PLATFORM')),
    ADD COLUMN initiated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN pickup_expected_at TIMESTAMPTZ,
    ADD COLUMN pickup_deadline TIMESTAMPTZ,
    ADD COLUMN first_failure_at TIMESTAMPTZ,
    ADD COLUMN delivery_retry_due_at TIMESTAMPTZ,
    ADD COLUMN valid_delivery_at TIMESTAMPTZ,
    ADD COLUMN otp_digest VARCHAR(128),
    ADD COLUMN otp_expires_at TIMESTAMPTZ,
    ADD COLUMN otp_attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(otp_attempt_count BETWEEN 0 AND 5),
    ADD COLUMN otp_consumed_at TIMESTAMPTZ,
    ADD CONSTRAINT uq_shipment_order_leg UNIQUE(order_id,leg),
    ADD CONSTRAINT ck_shipment_uc83 CHECK(workflow_model='LEGACY_V14' OR
        (delivery_method IS NOT NULL AND fee_snapshot IS NOT NULL AND fee_payer IS NOT NULL
          AND (delivery_method='CARRIER' OR fee_snapshot=0)
          AND (leg<>'RETURN' OR return_case_id IS NOT NULL)));
CREATE FUNCTION og_guard_return_shipment() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE c cases;
BEGIN
    IF NEW.workflow_model='UC83' AND NEW.leg='RETURN' THEN
        SELECT * INTO STRICT c FROM cases WHERE case_id=NEW.return_case_id FOR UPDATE;
        IF c.order_id<>NEW.order_id OR c.case_type<>'RETURN' OR c.approved_at IS NULL THEN
            RAISE EXCEPTION 'Return shipment requires approval for the same order' USING ERRCODE='23514';
        END IF;
        NEW.pickup_expected_at:=c.approved_at+INTERVAL '24 hours';
        NEW.pickup_deadline:=c.approved_at+INTERVAL '3 days';
    END IF;
    IF TG_OP='UPDATE' AND NEW.workflow_model='UC83' AND
        ROW(NEW.order_id,NEW.leg,NEW.return_case_id,NEW.delivery_method,NEW.initiated_at)
        IS DISTINCT FROM ROW(OLD.order_id,OLD.leg,OLD.return_case_id,OLD.delivery_method,OLD.initiated_at) THEN
        RAISE EXCEPTION 'Shipment identity/method snapshot cannot silently change' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_return_shipment_guard BEFORE INSERT OR UPDATE ON shipments
    FOR EACH ROW EXECUTE FUNCTION og_guard_return_shipment();
CREATE TABLE shipment_events (
    event_id UUID PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES shipments(shipment_id),
    source VARCHAR(30) NOT NULL,
    source_event_id VARCHAR(150) NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata JSONB NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(metadata)='object'),
    UNIQUE(source,source_event_id)
);
CREATE TRIGGER trg_shipment_event_history BEFORE UPDATE OR DELETE ON shipment_events
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
CREATE TABLE pickup_attempts (
    attempt_id UUID PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES shipments(shipment_id),
    attempt_no INTEGER NOT NULL CHECK(attempt_no BETWEEN 1 AND 3),
    attempted_at TIMESTAMPTZ NOT NULL,
    attempt_day DATE GENERATED ALWAYS AS ((attempted_at AT TIME ZONE 'Asia/Saigon')::DATE) STORED,
    outcome VARCHAR(15) NOT NULL CHECK(outcome IN ('FAILED','PICKED_UP')),
    responsibility VARCHAR(15) CHECK(responsibility IN ('BUYER','CARRIER','UNKNOWN','DISPUTED')),
    reason TEXT NOT NULL CHECK(btrim(reason)<>''),
    source_event_id UUID NOT NULL REFERENCES shipment_events(event_id),
    UNIQUE(shipment_id,attempt_no),
    UNIQUE(shipment_id,attempt_day),
    CHECK(outcome<>'FAILED' OR responsibility IS NOT NULL)
);
CREATE FUNCTION og_guard_pickup_attempt() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE s shipments;
BEGIN
    SELECT * INTO STRICT s FROM shipments WHERE shipment_id=NEW.shipment_id FOR UPDATE;
    IF s.workflow_model<>'UC83' OR s.leg<>'RETURN' OR NEW.attempted_at<s.initiated_at OR NEW.attempted_at>s.pickup_deadline
       OR NEW.attempt_no<>(SELECT count(*)+1 FROM pickup_attempts WHERE shipment_id=s.shipment_id)
       OR (SELECT count(*) FROM pickup_attempts WHERE shipment_id=s.shipment_id AND outcome='FAILED')>=3
       OR EXISTS(SELECT 1 FROM pickup_attempts WHERE shipment_id=s.shipment_id AND outcome='PICKED_UP')
       OR NOT EXISTS(SELECT 1 FROM shipment_events WHERE event_id=NEW.source_event_id AND shipment_id=s.shipment_id) THEN
        RAISE EXCEPTION 'Pickup deadline/count/source exceeded' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_pickup_attempt_guard BEFORE INSERT ON pickup_attempts
    FOR EACH ROW EXECUTE FUNCTION og_guard_pickup_attempt();
CREATE TRIGGER trg_pickup_attempt_history BEFORE UPDATE OR DELETE ON pickup_attempts
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();

CREATE TABLE handover_confirmations (
    confirmation_id UUID PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES shipments(shipment_id),
    party VARCHAR(10) NOT NULL CHECK(party IN ('BUYER','SELLER')),
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    outcome VARCHAR(15) NOT NULL CHECK(outcome IN ('SUCCESS','FAILED')),
    confirmed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    command_key VARCHAR(150) NOT NULL UNIQUE,
    UNIQUE(shipment_id,party)
);
CREATE FUNCTION og_guard_handover_party() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM shipments s JOIN orders o USING(order_id)
        WHERE s.shipment_id=NEW.shipment_id AND s.workflow_model='UC83'
          AND s.delivery_method IN ('SELF_PICKUP','SELF_DELIVERY')
          AND NEW.user_id=CASE NEW.party WHEN 'BUYER' THEN o.buyer_id ELSE o.seller_id END) THEN
        RAISE EXCEPTION 'Handover confirmation must belong to correct order party' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_handover_party_guard BEFORE INSERT ON handover_confirmations
    FOR EACH ROW EXECUTE FUNCTION og_guard_handover_party();
CREATE TRIGGER trg_handover_history BEFORE UPDATE OR DELETE ON handover_confirmations
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();

ALTER TABLE order_unboxing_evidences
    ADD COLUMN recorded_acknowledged_at TIMESTAMPTZ,
    ADD COLUMN skip_warning_accepted_at TIMESTAMPTZ,
    ADD COLUMN warning_version VARCHAR(50),
    ADD CONSTRAINT fk_unboxing_order_buyer FOREIGN KEY(order_id,buyer_id) REFERENCES orders(order_id,buyer_id) NOT VALID,
    ADD CONSTRAINT ck_unboxing_warning CHECK(skip_warning_accepted_at IS NULL OR warning_version IS NOT NULL);
-- Legacy complaint retention is conservative until canonical obligation checks can schedule deletion.
CREATE OR REPLACE FUNCTION fn_complaint_resolution_schedule_cleanup() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    NEW.evidence_cleanup_due_at := NULL;
    RETURN NEW;
END;
$$;
COMMENT ON COLUMN complaints.evidence_cleanup_due_at IS
    'Legacy automatic +3 days disabled. Recompute only after all related obligations finish; maximum 7 days thereafter.';

CREATE FUNCTION og_guard_case_round() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE c cases;
BEGIN
    SELECT * INTO STRICT c FROM cases WHERE case_id=NEW.case_id FOR UPDATE;
    IF (c.case_type='SYSTEM_ISSUE')<>(NEW.stage='SYSTEM_REVIEW') OR
        (NEW.stage='POST_RETURN_RESOLUTION' AND c.valid_returned_at IS NULL) THEN
        RAISE EXCEPTION 'Case round stage incompatible with case/delivery' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_case_round_guard BEFORE INSERT ON case_rounds
    FOR EACH ROW EXECUTE FUNCTION og_guard_case_round();
CREATE FUNCTION og_validate_case_state() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE c cases;
BEGIN
    SELECT * INTO STRICT c FROM cases WHERE case_id=NEW.case_id;
    IF (c.approved_at IS NOT NULL AND NOT EXISTS(SELECT 1 FROM case_decisions d JOIN case_rounds r USING(round_id)
        WHERE r.case_id=c.case_id AND d.outcome='APPROVE_RETURN' AND d.is_final))
        OR (c.state IN ('CLOSED','REJECTED') AND NOT EXISTS(SELECT 1 FROM case_decisions d JOIN case_rounds r USING(round_id)
            WHERE r.case_id=c.case_id AND d.is_final AND d.outcome IN
                ('REJECT_RETURN','FULL_GOODS_REFUND','EXEMPT_GOODS_REFUND','SYSTEM_RESOLVED')))
        OR (c.valid_returned_at IS NOT NULL AND NOT EXISTS(SELECT 1 FROM shipments s
            WHERE s.return_case_id=c.case_id AND s.leg='RETURN' AND s.valid_delivery_at=c.valid_returned_at)) THEN
        RAISE EXCEPTION 'Case state requires corresponding decision/delivery proof' USING ERRCODE='23514';
    END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER trg_case_state_proof AFTER INSERT OR UPDATE ON cases
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION og_validate_case_state();
CREATE FUNCTION og_close_case_holds() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    UPDATE money_holds SET closed_at=clock_timestamp() WHERE case_id=(SELECT r.case_id FROM case_rounds r
        WHERE r.round_id=NEW.round_id) AND closed_at IS NULL AND EXISTS(SELECT 1 FROM cases c
        WHERE c.case_id=money_holds.case_id AND c.state IN ('CLOSED','REJECTED'));
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_case_close_holds AFTER INSERT ON case_decisions
    FOR EACH ROW EXECUTE FUNCTION og_close_case_holds();
CREATE FUNCTION og_hold_new_case_component() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF NEW.component_type IN ('GOODS_CASH','PLATFORM_GOODS_SUBSIDY') THEN
        INSERT INTO money_holds(hold_id,component_id,source_key,reason,case_id)
            SELECT gen_random_uuid(),NEW.component_id,'RETURN_CASE:'||case_id,'Return case pending',case_id
            FROM cases WHERE order_id=NEW.order_id AND case_type='RETURN' AND state NOT IN ('CLOSED','REJECTED');
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_new_component_case_hold AFTER INSERT ON order_fund_components
    FOR EACH ROW EXECUTE FUNCTION og_hold_new_case_component();

-- Transaction primitives. The application authenticates the caller and verifies provider signatures.
CREATE FUNCTION og_confirm_direct_handover(p_shipment BIGINT) RETURNS BOOLEAN
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE s shipments; delivered TIMESTAMPTZ;
BEGIN
    PERFORM 1 FROM orders WHERE order_id=(SELECT order_id FROM shipments WHERE shipment_id=p_shipment) FOR UPDATE;
    SELECT * INTO STRICT s FROM shipments WHERE shipment_id=p_shipment FOR UPDATE;
    IF s.workflow_model<>'UC83' OR s.delivery_method='CARRIER' THEN
        RAISE EXCEPTION 'Direct handover only' USING ERRCODE='23514'; END IF;
    IF s.valid_delivery_at IS NOT NULL THEN RETURN TRUE; END IF;
    IF EXISTS(SELECT 1 FROM handover_confirmations WHERE shipment_id=p_shipment AND outcome='FAILED') THEN RETURN FALSE; END IF;
    IF s.otp_consumed_at IS NOT NULL THEN delivered:=s.otp_consumed_at;
    ELSIF (SELECT count(*) FROM handover_confirmations WHERE shipment_id=p_shipment AND outcome='SUCCESS')=2 THEN
        SELECT max(confirmed_at) INTO delivered FROM handover_confirmations WHERE shipment_id=p_shipment;
    ELSE RETURN FALSE; END IF;
    UPDATE shipments SET valid_delivery_at=delivered,status='DELIVERED',shipped_at=COALESCE(shipped_at,initiated_at),
        delivered_at=delivered WHERE shipment_id=p_shipment;
    IF s.leg='RETURN' THEN
        UPDATE cases SET state='POST_RETURN',valid_returned_at=delivered,seller_response_due_at=delivered+INTERVAL '2 days'
            WHERE case_id=s.return_case_id;
    ELSIF s.leg='OUTBOUND' THEN
        UPDATE orders SET status='DELIVERED',valid_delivered_at=delivered,
            return_due_at=CASE WHEN return_allowed THEN delivered+INTERVAL '3 days' END WHERE order_id=s.order_id;
    END IF;
    RETURN TRUE;
END;
$$;
CREATE FUNCTION og_consume_handover_otp(p_shipment BIGINT,p_buyer BIGINT,p_digest TEXT) RETURNS BOOLEAN
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE s shipments;
BEGIN
    PERFORM 1 FROM orders WHERE order_id=(SELECT order_id FROM shipments WHERE shipment_id=p_shipment) FOR UPDATE;
    SELECT * INTO STRICT s FROM shipments WHERE shipment_id=p_shipment FOR UPDATE;
    IF s.workflow_model<>'UC83' OR s.delivery_method='CARRIER' OR NOT EXISTS(SELECT 1 FROM orders
        WHERE order_id=s.order_id AND buyer_id=p_buyer) OR s.otp_digest IS NULL OR s.otp_consumed_at IS NOT NULL
        OR s.otp_expires_at<=clock_timestamp() OR s.otp_attempt_count>=5 THEN RETURN FALSE; END IF;
    UPDATE shipments SET otp_attempt_count=otp_attempt_count+1,
        otp_consumed_at=CASE WHEN otp_digest=p_digest THEN clock_timestamp() END WHERE shipment_id=p_shipment;
    IF s.otp_digest<>p_digest THEN RETURN FALSE; END IF;
    RETURN og_confirm_direct_handover(p_shipment);
END;
$$;
CREATE FUNCTION og_early_complete_order(p_order BIGINT,p_buyer BIGINT,p_warning TEXT,p_command TEXT) RETURNS BOOLEAN
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE o orders;
BEGIN
    SELECT * INTO STRICT o FROM orders WHERE order_id=p_order FOR UPDATE;
    IF EXISTS(SELECT 1 FROM order_events WHERE command_key=p_command AND order_id=p_order AND actor_id=p_buyer
        AND event_type='EARLY_COMPLETION_ACCEPTED') THEN RETURN TRUE; END IF;
    IF o.workflow_model<>'UC83' OR o.buyer_id<>p_buyer OR o.valid_delivered_at IS NULL
        OR NULLIF(btrim(p_warning),'') IS NULL OR o.status<>'DELIVERED' OR og_order_has_blocking_case(p_order)
        OR EXISTS(SELECT 1 FROM money_holds h JOIN order_fund_components c USING(component_id)
            WHERE c.order_id=p_order AND h.closed_at IS NULL) THEN
        RAISE EXCEPTION 'Early completion needs Buyer warning consent and no blockers' USING ERRCODE='23514'; END IF;
    UPDATE orders SET early_completed_at=clock_timestamp(),early_completion_warning_version=p_warning WHERE order_id=p_order;
    INSERT INTO order_events(event_id,order_id,actor_id,event_type,metadata,command_key)
        VALUES(gen_random_uuid(),p_order,p_buyer,'EARLY_COMPLETION_ACCEPTED',jsonb_build_object('warning_version',p_warning),p_command);
    RETURN TRUE;
END;
$$;
CREATE VIEW direct_handover_attention AS
    SELECT s.shipment_id,s.order_id,s.leg,
        CASE WHEN EXISTS(SELECT 1 FROM handover_confirmations h WHERE h.shipment_id=s.shipment_id AND outcome='FAILED')
            THEN 'CONFLICT_KTV' ELSE 'SILENT_14_DAYS' END AS reason
    FROM shipments s WHERE s.workflow_model='UC83' AND s.delivery_method<>'CARRIER' AND s.valid_delivery_at IS NULL
        AND (EXISTS(SELECT 1 FROM handover_confirmations h WHERE h.shipment_id=s.shipment_id AND outcome='FAILED')
            OR (s.initiated_at+INTERVAL '14 days'<=clock_timestamp() AND NOT EXISTS(
                SELECT 1 FROM handover_confirmations h WHERE h.shipment_id=s.shipment_id)));
CREATE VIEW case_cleanup_candidates AS
    SELECT c.case_id,c.last_related_completion_at+INTERVAL '7 days' AS cleanup_due_at
    FROM cases c WHERE c.state IN ('CLOSED','REJECTED') AND c.last_related_completion_at IS NOT NULL
      AND NOT EXISTS(SELECT 1 FROM money_holds h WHERE h.case_id=c.case_id AND h.closed_at IS NULL)
      AND NOT EXISTS(SELECT 1 FROM order_fund_components f WHERE f.order_id=c.order_id
          AND (f.reserved_amount<>0 OR f.refunded_amount+f.released_amount<f.confirmed_amount))
      AND NOT EXISTS(SELECT 1 FROM shipments s WHERE s.return_case_id=c.case_id AND s.status NOT IN ('DELIVERED','CANCELLED','RETURNED'));

CREATE FUNCTION og_validate_order_workflow_proof() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE o orders;
BEGIN
    SELECT * INTO STRICT o FROM orders WHERE order_id=NEW.order_id;
    IF o.workflow_model='UC83' AND (
        (o.paid_confirmed_at IS NOT NULL AND NOT EXISTS(SELECT 1 FROM payment_allocations a
            JOIN payment_confirmations c USING(confirmation_id) WHERE a.order_id=o.order_id
                AND c.disposition='ALLOCATABLE' AND c.confirmed_at=o.paid_confirmed_at))
        OR (o.valid_delivered_at IS NOT NULL AND NOT EXISTS(SELECT 1 FROM shipments s WHERE s.order_id=o.order_id
            AND s.leg='OUTBOUND' AND s.valid_delivery_at=o.valid_delivered_at))
        OR (o.early_completed_at IS NOT NULL AND NOT EXISTS(SELECT 1 FROM order_events e WHERE e.order_id=o.order_id
            AND e.actor_id=o.buyer_id AND e.event_type='EARLY_COMPLETION_ACCEPTED'))
        OR (o.seller_accept_due_at IS NOT NULL AND o.seller_accept_due_at<>
            COALESCE(o.paid_confirmed_at,o.created_at)+INTERVAL '2 days')) THEN
        RAISE EXCEPTION 'Order deadlines/payment/delivery/consent need source proof' USING ERRCODE='23514'; END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER trg_order_workflow_proof AFTER INSERT OR UPDATE ON orders
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION og_validate_order_workflow_proof();
