-- Trust-oriented Second-hand C2C Marketplace (O.G Shop)
-- Baseline Flyway Migration V1: Core Tables, pgvector & eKYC Biometrics

CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================================
-- 1. Identity & Access Management
-- ============================================================================

CREATE TABLE users (
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(320) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    full_name       VARCHAR(120) NOT NULL,
    phone_number    VARCHAR(20),
    avatar_url      TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ,

    CONSTRAINT ck_users_email_normalized CHECK (email = lower(btrim(email))),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'LOCKED', 'DEACTIVATED')),
    CONSTRAINT ck_users_deleted_state CHECK (deleted_at IS NULL OR status = 'DEACTIVATED')
);

CREATE UNIQUE INDEX uq_users_email ON users (email);
CREATE UNIQUE INDEX uq_users_phone_number ON users (phone_number) WHERE phone_number IS NOT NULL;

CREATE TABLE roles (
    role_id         SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name       VARCHAR(20) NOT NULL UNIQUE,
    description     VARCHAR(255),

    CONSTRAINT ck_roles_name CHECK (role_name IN ('BUYER', 'SELLER', 'ADMIN'))
);

CREATE TABLE user_roles (
    user_id         BIGINT NOT NULL,
    role_id         SMALLINT NOT NULL,
    granted_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by      BIGINT,

    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (role_id),
    CONSTRAINT fk_user_roles_granted_by FOREIGN KEY (granted_by) REFERENCES users (user_id)
);

CREATE INDEX ix_user_roles_role_id ON user_roles (role_id);
CREATE INDEX ix_user_roles_granted_by ON user_roles (granted_by) WHERE granted_by IS NOT NULL;

CREATE TABLE addresses (
    address_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    recipient_name  VARCHAR(120) NOT NULL,
    phone_number    VARCHAR(20) NOT NULL,
    province        VARCHAR(100) NOT NULL,
    district        VARCHAR(100) NOT NULL,
    ward            VARCHAR(100) NOT NULL,
    detail_address  VARCHAR(255) NOT NULL,
    is_default      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ,

    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE INDEX ix_addresses_user_id ON addresses (user_id);
CREATE UNIQUE INDEX uq_addresses_one_default_per_user
    ON addresses (user_id)
    WHERE is_default = TRUE AND deleted_at IS NULL;

-- ============================================================================
-- 2. Seller Verification & Biometric eKYC
-- ============================================================================

CREATE TABLE seller_verifications (
    verification_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL,
    verification_method   VARCHAR(30) NOT NULL DEFAULT 'MANUAL_ID_DOCUMENT',
    status                VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    document_data         JSONB NOT NULL DEFAULT '{}'::jsonb,
    rejection_reason      VARCHAR(500),
    submitted_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at           TIMESTAMPTZ,
    verified_by           BIGINT,

    CONSTRAINT fk_seller_verifications_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_seller_verifications_admin FOREIGN KEY (verified_by) REFERENCES users (user_id),
    CONSTRAINT ck_seller_verifications_method CHECK (verification_method IN ('MANUAL_ID_DOCUMENT', 'AI_EKYC')),
    CONSTRAINT ck_seller_verifications_status CHECK (status IN ('PENDING', 'VERIFIED', 'REJECTED')),
    CONSTRAINT ck_seller_verifications_document_object CHECK (jsonb_typeof(document_data) = 'object'),
    CONSTRAINT ck_seller_verifications_resolution CHECK (
        (status = 'PENDING' AND reviewed_at IS NULL AND verified_by IS NULL AND rejection_reason IS NULL)
        OR
        (status = 'VERIFIED' AND reviewed_at IS NOT NULL AND verified_by IS NOT NULL AND rejection_reason IS NULL)
        OR
        (status = 'REJECTED' AND reviewed_at IS NOT NULL AND verified_by IS NOT NULL AND rejection_reason IS NOT NULL)
    )
);

CREATE INDEX ix_seller_verifications_user_id ON seller_verifications (user_id);
CREATE INDEX ix_seller_verifications_verified_by ON seller_verifications (verified_by) WHERE verified_by IS NOT NULL;
CREATE INDEX ix_seller_verifications_status_submitted ON seller_verifications (status, submitted_at);
CREATE UNIQUE INDEX uq_seller_verifications_one_open_or_verified
    ON seller_verifications (user_id)
    WHERE status IN ('PENDING', 'VERIFIED');

CREATE TABLE seller_biometrics (
    biometric_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    verification_id     BIGINT NOT NULL,
    cccd_number         VARCHAR(20) NOT NULL,
    full_name           VARCHAR(120) NOT NULL,
    dob                 VARCHAR(20),
    hometown            TEXT,
    address             TEXT,
    face_embedding      vector(512) NOT NULL,
    match_distance      NUMERIC(5,4),
    card_front_url      TEXT,
    selfie_photo_url    TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_seller_biometrics_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_seller_biometrics_verification FOREIGN KEY (verification_id) REFERENCES seller_verifications (verification_id) ON DELETE CASCADE,
    CONSTRAINT uq_seller_biometrics_user UNIQUE (user_id),
    CONSTRAINT uq_seller_biometrics_cccd UNIQUE (cccd_number)
);

CREATE INDEX ix_seller_biometrics_user_id ON seller_biometrics (user_id);
CREATE INDEX ix_seller_biometrics_cccd ON seller_biometrics (cccd_number);
CREATE INDEX ix_seller_biometrics_embedding ON seller_biometrics USING ivfflat (face_embedding vector_cosine_ops) WITH (lists = 100);

-- ============================================================================
-- 3. Catalog & Products
-- ============================================================================

CREATE TABLE categories (
    category_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_category_id     BIGINT,
    category_name          VARCHAR(100) NOT NULL,
    slug                   VARCHAR(120) NOT NULL UNIQUE,
    description            VARCHAR(500),
    is_active              BOOLEAN NOT NULL DEFAULT TRUE,
    display_order          INTEGER NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ,

    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_category_id) REFERENCES categories (category_id),
    CONSTRAINT ck_categories_not_self_parent CHECK (parent_category_id IS NULL OR parent_category_id <> category_id),
    CONSTRAINT ck_categories_display_order CHECK (display_order >= 0),
    CONSTRAINT uq_categories_sibling_name UNIQUE NULLS NOT DISTINCT (parent_category_id, category_name)
);

CREATE INDEX ix_categories_parent_id ON categories (parent_category_id) WHERE parent_category_id IS NOT NULL;

CREATE TABLE products (
    product_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id               BIGINT NOT NULL,
    category_id             BIGINT NOT NULL,
    title                   VARCHAR(200) NOT NULL,
    description             TEXT NOT NULL,
    price                   NUMERIC(19,2) NOT NULL,
    currency                CHAR(3) NOT NULL DEFAULT 'VND',
    condition               VARCHAR(20) NOT NULL,
    usage_duration          VARCHAR(100),
    defects                 TEXT,
    repair_history          TEXT,
    included_accessories    TEXT,
    location                VARCHAR(255),
    status                  VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    reserved_until          TIMESTAMPTZ,
    reserved_order_id       BIGINT,
    version                 BIGINT NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ,
    deleted_at              TIMESTAMPTZ,

    CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES users (user_id),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (category_id),
    CONSTRAINT ck_products_price CHECK (price > 0),
    CONSTRAINT ck_products_currency CHECK (currency = 'VND'),
    CONSTRAINT ck_products_condition CHECK (condition IN ('LIKE_NEW', 'GOOD', 'FAIR', 'POOR', 'FOR_PARTS')),
    CONSTRAINT ck_products_status CHECK (status IN ('DRAFT', 'PENDING', 'ACTIVE', 'RESERVED', 'SOLD', 'HIDDEN', 'REJECTED')),
    CONSTRAINT ck_products_reservation CHECK (
        (status = 'RESERVED' AND reserved_until IS NOT NULL AND reserved_order_id IS NOT NULL)
        OR
        (status <> 'RESERVED' AND reserved_until IS NULL AND reserved_order_id IS NULL)
    ),
    CONSTRAINT ck_products_deleted_state CHECK (deleted_at IS NULL OR status IN ('HIDDEN', 'SOLD'))
);

CREATE INDEX ix_products_seller_status ON products (seller_id, status) WHERE deleted_at IS NULL;
CREATE INDEX ix_products_category_status_created ON products (category_id, status, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX ix_products_active_created ON products (created_at DESC) WHERE status = 'ACTIVE' AND deleted_at IS NULL;
CREATE INDEX ix_products_reservation_expiry ON products (reserved_until) WHERE status = 'RESERVED';
CREATE INDEX ix_products_reserved_order_id ON products (reserved_order_id) WHERE reserved_order_id IS NOT NULL;
CREATE INDEX ix_products_title_search ON products USING GIN (to_tsvector('simple', title));

CREATE TABLE product_media (
    media_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL,
    media_type      VARCHAR(10) NOT NULL,
    media_url       TEXT NOT NULL,
    display_order   INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_media_product FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT ck_product_media_type CHECK (media_type IN ('IMAGE', 'VIDEO')),
    CONSTRAINT ck_product_media_order CHECK (display_order >= 0),
    CONSTRAINT uq_product_media_order UNIQUE (product_id, display_order)
);

CREATE INDEX ix_product_media_product_id ON product_media (product_id);

-- ============================================================================
-- 4. Communication & Negotiations
-- ============================================================================

CREATE TABLE conversations (
    conversation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id         BIGINT NOT NULL,
    seller_id        BIGINT NOT NULL,
    product_id       BIGINT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_message_at  TIMESTAMPTZ,

    CONSTRAINT fk_conversations_buyer FOREIGN KEY (buyer_id) REFERENCES users (user_id),
    CONSTRAINT fk_conversations_seller FOREIGN KEY (seller_id) REFERENCES users (user_id),
    CONSTRAINT fk_conversations_product FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT ck_conversations_distinct_users CHECK (buyer_id <> seller_id),
    CONSTRAINT uq_conversations_parties_product UNIQUE (buyer_id, seller_id, product_id)
);

CREATE INDEX ix_conversations_buyer_recent ON conversations (buyer_id, last_message_at DESC NULLS LAST);
CREATE INDEX ix_conversations_seller_recent ON conversations (seller_id, last_message_at DESC NULLS LAST);
CREATE INDEX ix_conversations_product_id ON conversations (product_id);

CREATE TABLE messages (
    message_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT NOT NULL,
    sender_id        BIGINT NOT NULL,
    content          TEXT NOT NULL,
    message_type     VARCHAR(10) NOT NULL DEFAULT 'TEXT',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at          TIMESTAMPTZ,

    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (conversation_id),
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (user_id),
    CONSTRAINT ck_messages_type CHECK (message_type IN ('TEXT', 'IMAGE', 'SYSTEM')),
    CONSTRAINT ck_messages_content_not_blank CHECK (length(btrim(content)) > 0),
    CONSTRAINT ck_messages_read_time CHECK (read_at IS NULL OR read_at >= created_at)
);

CREATE INDEX ix_messages_conversation_created ON messages (conversation_id, created_at, message_id);
CREATE INDEX ix_messages_sender_id ON messages (sender_id);

CREATE TABLE offers (
    offer_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       BIGINT NOT NULL,
    buyer_id         BIGINT NOT NULL,
    seller_id        BIGINT NOT NULL,
    offer_price      NUMERIC(19,2) NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    expires_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at     TIMESTAMPTZ,

    CONSTRAINT fk_offers_product FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT fk_offers_buyer FOREIGN KEY (buyer_id) REFERENCES users (user_id),
    CONSTRAINT fk_offers_seller FOREIGN KEY (seller_id) REFERENCES users (user_id),
    CONSTRAINT ck_offers_distinct_users CHECK (buyer_id <> seller_id),
    CONSTRAINT ck_offers_price CHECK (offer_price > 0),
    CONSTRAINT ck_offers_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'COUNTERED', 'EXPIRED')),
    CONSTRAINT ck_offers_response CHECK (
        (status = 'PENDING' AND responded_at IS NULL)
        OR
        (status <> 'PENDING' AND responded_at IS NOT NULL)
    ),
    CONSTRAINT ck_offers_expiry CHECK (expires_at IS NULL OR expires_at > created_at)
);

CREATE INDEX ix_offers_product_status ON offers (product_id, status, created_at DESC);
CREATE INDEX ix_offers_buyer_status ON offers (buyer_id, status, created_at DESC);
CREATE INDEX ix_offers_seller_status ON offers (seller_id, status, created_at DESC);
CREATE UNIQUE INDEX uq_offers_one_pending_per_buyer_product
    ON offers (product_id, buyer_id)
    WHERE status = 'PENDING';

-- ============================================================================
-- 5. Commerce & Cart
-- ============================================================================

CREATE TABLE carts (
    cart_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL UNIQUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ,

    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE cart_items (
    cart_id          BIGINT NOT NULL,
    product_id       BIGINT NOT NULL,
    quantity         SMALLINT NOT NULL DEFAULT 1,
    added_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_cart_items PRIMARY KEY (cart_id, product_id),
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (cart_id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT ck_cart_items_mvp_quantity CHECK (quantity = 1)
);

CREATE INDEX ix_cart_items_product_id ON cart_items (product_id);

CREATE TABLE orders (
    order_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkout_group_id           UUID NOT NULL,
    buyer_id                    BIGINT NOT NULL,
    seller_id                   BIGINT NOT NULL,
    source_address_id           BIGINT,
    shipping_recipient_name     VARCHAR(120) NOT NULL,
    shipping_phone_number       VARCHAR(20) NOT NULL,
    shipping_province           VARCHAR(100) NOT NULL,
    shipping_district           VARCHAR(100) NOT NULL,
    shipping_ward               VARCHAR(100) NOT NULL,
    shipping_detail_address     VARCHAR(255) NOT NULL,
    subtotal                    NUMERIC(19,2) NOT NULL,
    shipping_fee                NUMERIC(19,2) NOT NULL DEFAULT 0,
    total_amount                NUMERIC(19,2) NOT NULL,
    currency                    CHAR(3) NOT NULL DEFAULT 'VND',
    status                      VARCHAR(30) NOT NULL DEFAULT 'PAYMENT_PENDING',
    payment_due_at              TIMESTAMPTZ NOT NULL,
    version                     BIGINT NOT NULL DEFAULT 0,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ,
    completed_at                TIMESTAMPTZ,
    cancelled_at                TIMESTAMPTZ,
    cancellation_reason         VARCHAR(500),

    CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users (user_id),
    CONSTRAINT fk_orders_seller FOREIGN KEY (seller_id) REFERENCES users (user_id),
    CONSTRAINT fk_orders_source_address FOREIGN KEY (source_address_id) REFERENCES addresses (address_id) ON DELETE SET NULL,
    CONSTRAINT ck_orders_distinct_users CHECK (buyer_id <> seller_id),
    CONSTRAINT ck_orders_amounts CHECK (subtotal > 0 AND shipping_fee >= 0 AND total_amount = subtotal + shipping_fee),
    CONSTRAINT ck_orders_currency CHECK (currency = 'VND'),
    CONSTRAINT ck_orders_status CHECK (status IN (
        'PAYMENT_PENDING', 'PAID_HELD', 'SELLER_CONFIRMED', 'SHIPPED', 'DELIVERED',
        'COMPLETED', 'CANCELLED', 'DISPUTED', 'REFUNDED'
    )),
    CONSTRAINT ck_orders_payment_due CHECK (payment_due_at > created_at),
    CONSTRAINT ck_orders_terminal_time CHECK (
        (status = 'COMPLETED' AND completed_at IS NOT NULL AND cancelled_at IS NULL AND cancellation_reason IS NULL)
        OR
        (status = 'CANCELLED' AND cancelled_at IS NOT NULL AND completed_at IS NULL AND cancellation_reason IS NOT NULL)
        OR
        (status NOT IN ('COMPLETED', 'CANCELLED') AND completed_at IS NULL AND cancelled_at IS NULL AND cancellation_reason IS NULL)
    )
);

CREATE INDEX ix_orders_buyer_created ON orders (buyer_id, created_at DESC);
CREATE INDEX ix_orders_seller_created ON orders (seller_id, created_at DESC);
CREATE INDEX ix_orders_checkout_group ON orders (buyer_id, checkout_group_id);
CREATE INDEX ix_orders_status_created ON orders (status, created_at);
CREATE INDEX ix_orders_source_address_id ON orders (source_address_id) WHERE source_address_id IS NOT NULL;
CREATE INDEX ix_orders_payment_expiry ON orders (payment_due_at) WHERE status = 'PAYMENT_PENDING';

CREATE TABLE order_items (
    order_item_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL,
    product_id       BIGINT NOT NULL,
    product_title    VARCHAR(200) NOT NULL,
    quantity         SMALLINT NOT NULL DEFAULT 1,
    unit_price       NUMERIC(19,2) NOT NULL,
    line_total       NUMERIC(19,2) NOT NULL,

    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_items_mvp_quantity CHECK (quantity = 1),
    CONSTRAINT ck_order_items_price CHECK (unit_price > 0 AND line_total = unit_price * quantity)
);

CREATE INDEX ix_order_items_product_id ON order_items (product_id);

ALTER TABLE products
    ADD CONSTRAINT fk_products_reserved_order_item
    FOREIGN KEY (reserved_order_id, product_id)
    REFERENCES order_items (order_id, product_id);

-- ============================================================================
-- 6. Payments (Escrow / Hold-Release) & Fulfillment
-- ============================================================================

CREATE TABLE payments (
    payment_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL UNIQUE,
    amount           NUMERIC(19,2) NOT NULL,
    currency         CHAR(3) NOT NULL DEFAULT 'VND',
    payment_method   VARCHAR(30) NOT NULL,
    transaction_code VARCHAR(100),
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    paid_at          TIMESTAMPTZ,
    version          BIGINT NOT NULL DEFAULT 0,
    held_at          TIMESTAMPTZ,
    released_at      TIMESTAMPTZ,
    refund_amount    NUMERIC(19,2),
    refund_reason    VARCHAR(500),
    refunded_at      TIMESTAMPTZ,
    failure_reason   VARCHAR(500),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ,

    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT uq_payments_transaction_code UNIQUE (transaction_code),
    CONSTRAINT ck_payments_amount CHECK (amount > 0),
    CONSTRAINT ck_payments_currency CHECK (currency = 'VND'),
    CONSTRAINT ck_payments_method CHECK (payment_method IN ('COD_MOCK', 'BANK_TRANSFER_MOCK', 'E_WALLET_MOCK')),
    CONSTRAINT ck_payments_status CHECK (status IN ('PENDING', 'PAID', 'HELD', 'RELEASED', 'REFUND_PENDING', 'REFUNDED', 'FAILED')),
    CONSTRAINT ck_payments_refund_amount CHECK (refund_amount IS NULL OR refund_amount = amount),
    CONSTRAINT ck_payments_state_fields CHECK (
        (status = 'PENDING' AND paid_at IS NULL AND held_at IS NULL AND released_at IS NULL AND refunded_at IS NULL AND failure_reason IS NULL)
        OR
        (status = 'PAID' AND paid_at IS NOT NULL AND held_at IS NULL AND released_at IS NULL AND refunded_at IS NULL AND failure_reason IS NULL)
        OR
        (status = 'HELD' AND paid_at IS NOT NULL AND held_at IS NOT NULL AND held_at >= paid_at AND released_at IS NULL AND refunded_at IS NULL AND failure_reason IS NULL)
        OR
        (status = 'RELEASED' AND paid_at IS NOT NULL AND held_at IS NOT NULL AND held_at >= paid_at AND released_at IS NOT NULL AND released_at >= held_at AND refunded_at IS NULL AND failure_reason IS NULL)
        OR
        (status = 'REFUND_PENDING' AND paid_at IS NOT NULL AND held_at IS NOT NULL AND held_at >= paid_at AND released_at IS NULL AND refunded_at IS NULL AND refund_amount IS NOT NULL AND refund_reason IS NOT NULL AND failure_reason IS NULL)
        OR
        (status = 'REFUNDED' AND paid_at IS NOT NULL AND held_at IS NOT NULL AND held_at >= paid_at AND released_at IS NULL AND refunded_at IS NOT NULL AND refunded_at >= held_at AND refund_amount IS NOT NULL AND refund_reason IS NOT NULL AND failure_reason IS NULL)
        OR
        (status = 'FAILED' AND paid_at IS NULL AND held_at IS NULL AND released_at IS NULL AND refunded_at IS NULL AND failure_reason IS NOT NULL)
    )
);

CREATE INDEX ix_payments_status_created ON payments (status, created_at);

CREATE TABLE shipments (
    shipment_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL UNIQUE,
    carrier          VARCHAR(100),
    tracking_number  VARCHAR(100),
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    shipped_at       TIMESTAMPTZ,
    delivered_at     TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ,

    CONSTRAINT fk_shipments_order FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT uq_shipments_tracking_number UNIQUE (tracking_number),
    CONSTRAINT ck_shipments_status CHECK (status IN ('PENDING', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'RETURNED', 'FAILED')),
    CONSTRAINT ck_shipments_times CHECK (
        (status = 'PENDING' AND shipped_at IS NULL AND delivered_at IS NULL)
        OR
        (status IN ('PICKED_UP', 'IN_TRANSIT', 'RETURNED') AND shipped_at IS NOT NULL AND delivered_at IS NULL)
        OR
        (status = 'DELIVERED' AND shipped_at IS NOT NULL AND delivered_at IS NOT NULL AND delivered_at >= shipped_at)
        OR
        (status = 'FAILED' AND delivered_at IS NULL)
    )
);

CREATE INDEX ix_shipments_status_updated ON shipments (status, updated_at);

-- ============================================================================
-- 7. Trust, Reviews, Complaints & Reports
-- ============================================================================

CREATE TABLE reviews (
    review_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL,
    reviewer_id      BIGINT NOT NULL,
    reviewee_id      BIGINT NOT NULL,
    rating           SMALLINT NOT NULL,
    comment          VARCHAR(2000),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ,
    deleted_at       TIMESTAMPTZ,

    CONSTRAINT fk_reviews_order FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT fk_reviews_reviewer FOREIGN KEY (reviewer_id) REFERENCES users (user_id),
    CONSTRAINT fk_reviews_reviewee FOREIGN KEY (reviewee_id) REFERENCES users (user_id),
    CONSTRAINT ck_reviews_distinct_users CHECK (reviewer_id <> reviewee_id),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT uq_reviews_order_parties UNIQUE (order_id, reviewer_id, reviewee_id)
);

CREATE INDEX ix_reviews_reviewer_id ON reviews (reviewer_id);
CREATE INDEX ix_reviews_reviewee_created ON reviews (reviewee_id, created_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE complaints (
    complaint_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL,
    created_by       BIGINT NOT NULL,
    reason           VARCHAR(50) NOT NULL,
    description      TEXT NOT NULL,
    evidence         JSONB NOT NULL DEFAULT '{"images": [], "videos": []}'::jsonb,
    status           VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    resolution       VARCHAR(30),
    resolution_note  TEXT,
    resolved_by      BIGINT,
    refund_amount    NUMERIC(19,2),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at      TIMESTAMPTZ,

    CONSTRAINT fk_complaints_order FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT fk_complaints_created_by FOREIGN KEY (created_by) REFERENCES users (user_id),
    CONSTRAINT fk_complaints_resolved_by FOREIGN KEY (resolved_by) REFERENCES users (user_id),
    CONSTRAINT ck_complaints_reason CHECK (reason IN ('NOT_AS_DESCRIBED', 'DAMAGED', 'COUNTERFEIT', 'MISSING_ITEM', 'DELIVERY_ISSUE', 'OTHER')),
    CONSTRAINT ck_complaints_evidence_object CHECK (jsonb_typeof(evidence) = 'object'),
    CONSTRAINT ck_complaints_status CHECK (status IN ('OPEN', 'REVIEWING', 'RESOLVED', 'REJECTED')),
    CONSTRAINT ck_complaints_resolution CHECK (resolution IS NULL OR resolution IN ('REFUND_BUYER', 'RELEASE_TO_SELLER', 'REJECT_COMPLAINT')),
    CONSTRAINT ck_complaints_refund CHECK (refund_amount IS NULL OR refund_amount > 0),
    CONSTRAINT ck_complaints_resolution_fields CHECK (
        (status IN ('OPEN', 'REVIEWING') AND resolution IS NULL AND resolved_by IS NULL AND resolved_at IS NULL AND refund_amount IS NULL)
        OR
        (status = 'RESOLVED' AND resolution IN ('REFUND_BUYER', 'RELEASE_TO_SELLER') AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL)
        OR
        (status = 'REJECTED' AND resolution = 'REJECT_COMPLAINT' AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL AND refund_amount IS NULL)
    ),
    CONSTRAINT ck_complaints_refund_resolution CHECK (
        (resolution = 'REFUND_BUYER' AND refund_amount IS NOT NULL)
        OR (resolution IS DISTINCT FROM 'REFUND_BUYER' AND refund_amount IS NULL)
    )
);

CREATE INDEX ix_complaints_order_id ON complaints (order_id);
CREATE INDEX ix_complaints_created_by ON complaints (created_by);
CREATE INDEX ix_complaints_resolved_by ON complaints (resolved_by) WHERE resolved_by IS NOT NULL;
CREATE INDEX ix_complaints_status_created ON complaints (status, created_at);
CREATE UNIQUE INDEX uq_complaints_one_active_per_order
    ON complaints (order_id)
    WHERE status IN ('OPEN', 'REVIEWING');

CREATE TABLE reports (
    report_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id       BIGINT NOT NULL,
    reported_user_id  BIGINT,
    product_id        BIGINT,
    reason            VARCHAR(30) NOT NULL,
    description       TEXT,
    status            VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    resolution_note   TEXT,
    resolved_by       BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at       TIMESTAMPTZ,

    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users (user_id),
    CONSTRAINT fk_reports_reported_user FOREIGN KEY (reported_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_reports_product FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT fk_reports_resolved_by FOREIGN KEY (resolved_by) REFERENCES users (user_id),
    CONSTRAINT ck_reports_target CHECK (reported_user_id IS NOT NULL OR product_id IS NOT NULL),
    CONSTRAINT ck_reports_not_self CHECK (reported_user_id IS NULL OR reporter_id <> reported_user_id),
    CONSTRAINT ck_reports_reason CHECK (reason IN ('FAKE_LISTING', 'SPAM', 'HARASSMENT', 'SUSPICIOUS_ACCOUNT', 'PROHIBITED_CONTENT', 'OTHER')),
    CONSTRAINT ck_reports_status CHECK (status IN ('OPEN', 'REVIEWING', 'RESOLVED', 'REJECTED')),
    CONSTRAINT ck_reports_resolution_fields CHECK (
        (status IN ('OPEN', 'REVIEWING') AND resolved_by IS NULL AND resolved_at IS NULL)
        OR
        (status IN ('RESOLVED', 'REJECTED') AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL)
    )
);

CREATE INDEX ix_reports_reporter_id ON reports (reporter_id);
CREATE INDEX ix_reports_reported_user_id ON reports (reported_user_id) WHERE reported_user_id IS NOT NULL;
CREATE INDEX ix_reports_product_id ON reports (product_id) WHERE product_id IS NOT NULL;
CREATE INDEX ix_reports_resolved_by ON reports (resolved_by) WHERE resolved_by IS NOT NULL;
CREATE INDEX ix_reports_status_created ON reports (status, created_at);

-- ============================================================================
-- 8. Platform: Notifications & Audit Logs
-- ============================================================================

CREATE TABLE notifications (
    notification_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    type             VARCHAR(50) NOT NULL,
    title            VARCHAR(200) NOT NULL,
    content          TEXT NOT NULL,
    reference_type   VARCHAR(50),
    reference_id     BIGINT,
    is_read          BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at          TIMESTAMPTZ,

    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT ck_notifications_read CHECK (
        (is_read = FALSE AND read_at IS NULL)
        OR (is_read = TRUE AND read_at IS NOT NULL AND read_at >= created_at)
    ),
    CONSTRAINT ck_notifications_reference CHECK (
        (reference_type IS NULL AND reference_id IS NULL)
        OR (reference_type IS NOT NULL AND reference_id IS NOT NULL)
    )
);

CREATE INDEX ix_notifications_user_unread ON notifications (user_id, created_at DESC) WHERE is_read = FALSE;
CREATE INDEX ix_notifications_user_created ON notifications (user_id, created_at DESC);

CREATE TABLE audit_logs (
    log_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT,
    action           VARCHAR(50) NOT NULL,
    entity_type      VARCHAR(50) NOT NULL,
    entity_id        BIGINT,
    old_values       JSONB,
    new_values       JSONB,
    ip_address       INET,
    request_id       VARCHAR(100),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT ck_audit_logs_old_values CHECK (old_values IS NULL OR jsonb_typeof(old_values) = 'object'),
    CONSTRAINT ck_audit_logs_new_values CHECK (new_values IS NULL OR jsonb_typeof(new_values) = 'object')
);

CREATE INDEX ix_audit_logs_user_created ON audit_logs (user_id, created_at DESC) WHERE user_id IS NOT NULL;
CREATE INDEX ix_audit_logs_entity_created ON audit_logs (entity_type, entity_id, created_at DESC);
CREATE INDEX ix_audit_logs_action_created ON audit_logs (action, created_at DESC);

-- ============================================================================
-- 9. Seed Data: Core Roles
-- ============================================================================

INSERT INTO roles (role_name, description) VALUES
    ('BUYER', 'Default marketplace buyer role'),
    ('SELLER', 'Verified seller role'),
    ('ADMIN', 'System administrator role');
