-- G10/G11/G12. Shared events and projections, not one notification table per UC.
CREATE TABLE account_restrictions (
    restriction_id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    scope VARCHAR(25) NOT NULL CHECK(scope IN ('NEW_TRANSACTIONS','LOGIN')),
    imposed_by BIGINT NOT NULL REFERENCES users(user_id),
    reason TEXT NOT NULL CHECK(btrim(reason)<>''),
    source_key VARCHAR(150) NOT NULL,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMPTZ,
    UNIQUE(user_id,source_key),
    CHECK(closed_at IS NULL OR closed_at>=opened_at)
);
CREATE INDEX ix_account_restrictions_open ON account_restrictions(user_id,scope) WHERE closed_at IS NULL;
CREATE FUNCTION og_guard_account_restriction() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    PERFORM 1 FROM users WHERE user_id=NEW.user_id FOR UPDATE;
    IF NOT (og_has_role(NEW.imposed_by,'KTV') OR og_has_role(NEW.imposed_by,'ADMIN')) THEN
        RAISE EXCEPTION 'Restriction needs KTV/Admin authority' USING ERRCODE='23514';
    END IF;
    IF NEW.scope='LOGIN' AND NEW.closed_at IS NULL AND (
        EXISTS(SELECT 1 FROM orders o WHERE NEW.user_id IN (o.buyer_id,o.seller_id)
            AND o.status NOT IN ('COMPLETED','CANCELLED','REFUNDED'))
        OR EXISTS(SELECT 1 FROM cases c LEFT JOIN orders o USING(order_id)
            WHERE c.state NOT IN ('CLOSED','REJECTED')
                AND NEW.user_id IN (c.created_by,o.buyer_id,o.seller_id))) THEN
        RAISE EXCEPTION 'Open obligations require login access; restrict new transactions instead' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_account_restriction_guard BEFORE INSERT OR UPDATE ON account_restrictions
    FOR EACH ROW EXECUTE FUNCTION og_guard_account_restriction();
CREATE TABLE seller_buyer_blocks (
    seller_id BIGINT NOT NULL REFERENCES users(user_id),
    buyer_id BIGINT NOT NULL REFERENCES users(user_id),
    blocked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unblocked_at TIMESTAMPTZ,
    reason TEXT,
    PRIMARY KEY(seller_id,buyer_id),
    CHECK(seller_id<>buyer_id),
    CHECK(unblocked_at IS NULL OR unblocked_at>=blocked_at)
);
CREATE TABLE penalty_policies (
    policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_code VARCHAR(60) NOT NULL UNIQUE,
    thresholds JSONB NOT NULL CHECK(jsonb_typeof(thresholds)='array'),
    created_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_penalty_policy_history BEFORE UPDATE OR DELETE ON penalty_policies
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
ALTER TABLE reports ADD COLUMN message_id BIGINT REFERENCES messages(message_id),
    ADD COLUMN incident_key VARCHAR(150), ADD COLUMN evidence_snapshot JSONB;
CREATE INDEX ix_report_incident ON reports(incident_key) WHERE incident_key IS NOT NULL;
CREATE TABLE penalty_ledger (
    entry_id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    report_id BIGINT REFERENCES reports(report_id),
    policy_id BIGINT NOT NULL REFERENCES penalty_policies(policy_id),
    points_delta INTEGER NOT NULL CHECK(points_delta<>0),
    adjustment_of UUID REFERENCES penalty_ledger(entry_id),
    decided_by BIGINT NOT NULL REFERENCES users(user_id),
    reason TEXT NOT NULL CHECK(btrim(reason)<>''),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    command_key VARCHAR(150) NOT NULL UNIQUE,
    CHECK((points_delta>0 AND report_id IS NOT NULL) OR (points_delta<0 AND adjustment_of IS NOT NULL))
);
CREATE UNIQUE INDEX uq_penalty_report_user ON penalty_ledger(report_id,user_id) WHERE adjustment_of IS NULL;
CREATE FUNCTION og_guard_penalty_entry() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE points BIGINT;
BEGIN
    PERFORM 1 FROM users WHERE user_id=NEW.user_id FOR UPDATE;
    SELECT COALESCE(sum(points_delta),0) INTO points FROM penalty_ledger WHERE user_id=NEW.user_id;
    IF NOT og_has_role(NEW.decided_by,'KTV') OR points+NEW.points_delta<0
        OR (NEW.points_delta>0 AND NOT EXISTS(SELECT 1 FROM reports
            WHERE report_id=NEW.report_id AND status='RESOLVED'))
        OR (NEW.adjustment_of IS NOT NULL AND NOT EXISTS(SELECT 1 FROM penalty_ledger
            WHERE entry_id=NEW.adjustment_of AND user_id=NEW.user_id)) THEN
        RAISE EXCEPTION 'Penalty requires confirmed KTV violation/correction' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_penalty_entry_guard BEFORE INSERT ON penalty_ledger
    FOR EACH ROW EXECUTE FUNCTION og_guard_penalty_entry();
CREATE TRIGGER trg_penalty_entry_history BEFORE UPDATE OR DELETE ON penalty_ledger
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();

CREATE TABLE review_revisions (
    revision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL REFERENCES reviews(review_id),
    original_record JSONB NOT NULL CHECK(jsonb_typeof(original_record)='object'),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE FUNCTION og_guard_review_parties() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE o orders;
BEGIN
    SELECT * INTO STRICT o FROM orders WHERE order_id=NEW.order_id;
    IF NOT ((NEW.reviewer_id=o.buyer_id AND NEW.reviewee_id=o.seller_id)
        OR (NEW.reviewer_id=o.seller_id AND NEW.reviewee_id=o.buyer_id))
        OR (o.workflow_model='UC83' AND o.valid_delivered_at IS NULL)
        OR (o.workflow_model='LEGACY_V14' AND o.status NOT IN ('DELIVERED','COMPLETED')) THEN
        RAISE EXCEPTION 'Review requires delivered order and its two parties' USING ERRCODE='23514';
    END IF;
    IF TG_OP='UPDATE' THEN
        IF ROW(NEW.order_id,NEW.reviewer_id,NEW.reviewee_id) IS DISTINCT FROM ROW(OLD.order_id,OLD.reviewer_id,OLD.reviewee_id) THEN
            RAISE EXCEPTION 'Review identity immutable' USING ERRCODE='23514';
        END IF;
        INSERT INTO review_revisions(review_id,original_record) VALUES(OLD.review_id,to_jsonb(OLD));
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_review_party_guard BEFORE INSERT OR UPDATE ON reviews
    FOR EACH ROW EXECUTE FUNCTION og_guard_review_parties();
CREATE TRIGGER trg_review_revision_history BEFORE UPDATE OR DELETE ON review_revisions
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
CREATE TRIGGER trg_audit_history BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
CREATE TABLE account_status_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    old_status VARCHAR(20),
    new_status VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE FUNCTION og_record_account_status() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF TG_OP='INSERT' OR NEW.status IS DISTINCT FROM OLD.status THEN
        INSERT INTO account_status_events(user_id,old_status,new_status)
            VALUES(NEW.user_id,CASE WHEN TG_OP='UPDATE' THEN OLD.status ELSE NULL END,NEW.status);
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_account_status_event AFTER INSERT OR UPDATE OF status ON users
    FOR EACH ROW EXECUTE FUNCTION og_record_account_status();
CREATE TRIGGER trg_account_status_history BEFORE UPDATE OR DELETE ON account_status_events
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
COMMENT ON TABLE account_status_events IS 'History starts at V20. Do not fabricate activity before migration.';

CREATE TABLE notification_dispatches (
    dispatch_id UUID PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES users(user_id),
    event_id UUID NOT NULL UNIQUE REFERENCES outbox_events(event_id),
    title VARCHAR(200) NOT NULL CHECK(btrim(title)<>''),
    content TEXT NOT NULL CHECK(btrim(content)<>''),
    target_data JSONB NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(target_data)='object'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    command_key VARCHAR(150) NOT NULL UNIQUE
);
CREATE FUNCTION og_guard_admin_dispatch() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF NOT og_has_role(NEW.sender_id,'ADMIN') THEN
        RAISE EXCEPTION 'Only Admin sends manual dispatch' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_admin_dispatch_guard BEFORE INSERT ON notification_dispatches
    FOR EACH ROW EXECUTE FUNCTION og_guard_admin_dispatch();
CREATE TRIGGER trg_dispatch_history BEFORE UPDATE OR DELETE ON notification_dispatches
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();
ALTER TABLE notifications
    ADD COLUMN event_id UUID REFERENCES outbox_events(event_id),
    ADD COLUMN dispatch_id UUID REFERENCES notification_dispatches(dispatch_id),
    ADD COLUMN sender_id BIGINT REFERENCES users(user_id),
    ADD COLUMN reference_uuid UUID,
    ADD COLUMN reference_revision BIGINT,
    ADD COLUMN target_data JSONB NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(target_data)='object');
CREATE UNIQUE INDEX uq_notification_event_recipient ON notifications(event_id,user_id) WHERE event_id IS NOT NULL;
CREATE UNIQUE INDEX uq_dispatch_recipient ON notifications(dispatch_id,user_id) WHERE dispatch_id IS NOT NULL;
CREATE INDEX ix_notification_cursor ON notifications(user_id,created_at DESC,notification_id DESC);
CREATE FUNCTION og_guard_manual_recipient() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE d notification_dispatches;
BEGIN
    IF NEW.dispatch_id IS NOT NULL THEN
        SELECT * INTO STRICT d FROM notification_dispatches WHERE dispatch_id=NEW.dispatch_id;
        IF NOT (og_has_role(NEW.user_id,'BUYER') OR og_has_role(NEW.user_id,'SELLER') OR og_has_role(NEW.user_id,'KTV')) THEN
            RAISE EXCEPTION 'Manual recipient must be Buyer/Seller/KTV' USING ERRCODE='23514';
        END IF;
        NEW.sender_id:=d.sender_id; NEW.event_id:=d.event_id; NEW.title:=d.title; NEW.content:=d.content;
        NEW.target_data:=d.target_data;
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_manual_recipient_guard BEFORE INSERT ON notifications
    FOR EACH ROW EXECUTE FUNCTION og_guard_manual_recipient();
CREATE TABLE notification_deliveries (
    delivery_id UUID PRIMARY KEY,
    notification_id BIGINT NOT NULL REFERENCES notifications(notification_id),
    channel VARCHAR(15) NOT NULL CHECK(channel IN ('IN_APP','EMAIL')),
    state VARCHAR(15) NOT NULL DEFAULT 'PENDING' CHECK(state IN ('PENDING','SENT','FAILED')),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(attempt_count>=0),
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMPTZ,
    last_error VARCHAR(1000),
    UNIQUE(notification_id,channel),
    CHECK(state<>'SENT' OR sent_at IS NOT NULL)
);
CREATE INDEX ix_notification_delivery_pending ON notification_deliveries(available_at) WHERE state IN ('PENDING','FAILED');
CREATE TABLE notification_reminders (
    reminder_id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    source_key VARCHAR(150) NOT NULL,
    reminder_type VARCHAR(30) NOT NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    state VARCHAR(15) NOT NULL DEFAULT 'PENDING' CHECK(state IN ('PENDING','SENT','CANCELLED')),
    source_snapshot JSONB NOT NULL CHECK(jsonb_typeof(source_snapshot)='object'),
    UNIQUE(user_id,source_key,scheduled_at),
    CHECK(expires_at>=scheduled_at)
);
CREATE TABLE outbox_consumer_checkpoints (
    consumer_name VARCHAR(100) NOT NULL,
    event_id UUID NOT NULL REFERENCES outbox_events(event_id),
    processed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(consumer_name,event_id)
);
CREATE TRIGGER trg_outbox_checkpoint_history BEFORE UPDATE OR DELETE ON outbox_consumer_checkpoints
    FOR EACH ROW EXECUTE FUNCTION og_reject_history_mutation();

CREATE TABLE interaction_events (
    event_id UUID PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id),
    guest_session_digest CHAR(64),
    event_type VARCHAR(15) NOT NULL CHECK(event_type IN ('SEARCH','VIEW')),
    product_id BIGINT REFERENCES products(product_id),
    query_text VARCHAR(200),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_key VARCHAR(150) NOT NULL UNIQUE,
    CHECK((user_id IS NOT NULL)::INTEGER+(guest_session_digest IS NOT NULL)::INTEGER=1),
    CHECK(event_type<>'VIEW' OR product_id IS NOT NULL)
);
CREATE INDEX ix_interaction_product_metric ON interaction_events(product_id,event_type,occurred_at);
CREATE INDEX ix_interaction_user_recent ON interaction_events(user_id,occurred_at DESC);
CREATE TABLE report_export_runs (
    export_id UUID PRIMARY KEY,
    requested_by BIGINT NOT NULL REFERENCES users(user_id),
    metric VARCHAR(30) NOT NULL CHECK(metric IN ('USERS','LISTING_REVENUE','SEARCH','VIEW','PURCHASE','RETURN_CASES','SYSTEM_ISSUES')),
    filters JSONB NOT NULL CHECK(jsonb_typeof(filters)='object'),
    timezone VARCHAR(60) NOT NULL DEFAULT 'Asia/Saigon',
    cutoff_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    object_key TEXT
);
CREATE VIEW listing_revenue_entries AS
    SELECT r.receipt_id,a.product_id,a.revision_id,a.policy_id,a.assessment_id,r.amount,r.confirmed_at
    FROM listing_fee_receipts r JOIN listing_fee_charges c USING(charge_id)
        JOIN listing_fee_assessments a USING(assessment_id);
CREATE VIEW completed_case_statistics AS
    SELECT c.case_id,c.case_type,c.order_id,c.closed_at,d.outcome,d.goods_refund_amount
    FROM cases c LEFT JOIN LATERAL(
        SELECT decision.outcome,decision.goods_refund_amount FROM case_decisions decision
        JOIN case_rounds round USING(round_id) WHERE round.case_id=c.case_id AND decision.is_final
        ORDER BY decision.decided_at DESC,decision.decision_id DESC LIMIT 1
    ) d ON TRUE WHERE c.state IN ('CLOSED','REJECTED');
CREATE VIEW reputation_summary AS
    SELECT u.user_id,COALESCE(r.average_stars,0) AS average_stars,COALESCE(r.review_count,0) AS review_count,
        COALESCE(p.penalty_points,0) AS penalty_points,
        CASE WHEN r.review_count IS NULL THEN NULL ELSE r.average_stars-COALESCE(p.penalty_points,0) END AS reputation
    FROM users u LEFT JOIN (
        SELECT reviewee_id,avg(rating) AS average_stars,count(*) AS review_count
        FROM reviews rv JOIN orders o USING(order_id) WHERE rv.deleted_at IS NULL
          AND ((rv.reviewer_id=o.buyer_id AND rv.reviewee_id=o.seller_id) OR
               (rv.reviewer_id=o.seller_id AND rv.reviewee_id=o.buyer_id))
          AND ((o.workflow_model='UC83' AND o.valid_delivered_at IS NOT NULL) OR
               (o.workflow_model='LEGACY_V14' AND o.status IN ('DELIVERED','COMPLETED')))
          GROUP BY reviewee_id
    ) r ON r.reviewee_id=u.user_id LEFT JOIN (
        SELECT user_id,sum(points_delta) AS penalty_points FROM penalty_ledger GROUP BY user_id
    ) p ON p.user_id=u.user_id;
CREATE VIEW uc83_public_products AS
    SELECT p.* FROM products p JOIN users seller ON seller.user_id=p.seller_id
    WHERE p.workflow_model='UC83' AND p.status='ACTIVE' AND p.deleted_at IS NULL AND p.quantity_available>0
      AND seller.status='ACTIVE' AND NOT EXISTS(SELECT 1 FROM account_restrictions ar
        WHERE ar.user_id=p.seller_id AND ar.closed_at IS NULL);

CREATE FUNCTION og_guard_new_transaction() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE o orders;
BEGIN
    SELECT o1.* INTO STRICT o FROM order_items i JOIN orders o1 USING(order_id) WHERE i.order_item_id=NEW.order_item_id;
    PERFORM 1 FROM users WHERE user_id IN (o.buyer_id,o.seller_id) ORDER BY user_id FOR UPDATE;
    IF NOT og_has_role(o.buyer_id,'BUYER') OR NOT og_has_role(o.seller_id,'SELLER')
        OR EXISTS(SELECT 1 FROM account_restrictions WHERE user_id IN (o.buyer_id,o.seller_id) AND closed_at IS NULL)
        OR EXISTS(SELECT 1 FROM seller_buyer_blocks WHERE seller_id=o.seller_id AND buyer_id=o.buyer_id AND unblocked_at IS NULL)
        OR NOT EXISTS(SELECT 1 FROM seller_profiles s JOIN ekyc_profiles e ON e.profile_id=s.ekyc_profile_id
            JOIN ekyc_decisions d ON d.profile_id=e.profile_id WHERE s.user_id=o.seller_id AND s.state='APPROVED'
                AND e.state='VERIFIED' AND d.outcome='VERIFIED' AND e.reference_expires_at>clock_timestamp())
        OR EXISTS(SELECT 1 FROM ekyc_profiles WHERE user_id=o.seller_id AND state IN ('DRAFT','IN_PROGRESS','PENDING')) THEN
        RAISE EXCEPTION 'New transaction blocked by identity/restriction/party block' USING ERRCODE='23514'; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_new_transaction_guard BEFORE INSERT ON inventory_reservations
    FOR EACH ROW EXECUTE FUNCTION og_guard_new_transaction();
CREATE FUNCTION og_guard_export_authority() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF NOT og_has_role(NEW.requested_by,'ADMIN') THEN RAISE EXCEPTION 'Admin export only' USING ERRCODE='23514'; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_export_authority BEFORE INSERT ON report_export_runs
    FOR EACH ROW EXECUTE FUNCTION og_guard_export_authority();
