-- Identity sessions and privacy-preserving eKYC metadata.

INSERT INTO roles (role_name, description)
VALUES
    ('BUYER', 'Can browse and buy products'),
    ('SELLER', 'Can list products after seller verification'),
    ('ADMIN', 'Administrative access; never granted by public APIs')
ON CONFLICT (role_name) DO NOTHING;

CREATE TABLE refresh_sessions (
    session_id       UUID PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    family_id        UUID NOT NULL,
    token_digest     VARCHAR(64) NOT NULL,
    issued_at        TIMESTAMPTZ NOT NULL,
    expires_at       TIMESTAMPTZ NOT NULL,
    consumed_at      TIMESTAMPTZ,
    revoked_at       TIMESTAMPTZ,
    replaced_by      UUID,
    created_by_ip    VARCHAR(45),
    user_agent       VARCHAR(255),

    CONSTRAINT fk_refresh_sessions_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_refresh_sessions_replacement FOREIGN KEY (replaced_by) REFERENCES refresh_sessions (session_id),
    CONSTRAINT uq_refresh_sessions_token_digest UNIQUE (token_digest),
    CONSTRAINT ck_refresh_sessions_expiry CHECK (expires_at > issued_at),
    CONSTRAINT ck_refresh_sessions_digest_length CHECK (length(token_digest) = 64)
);

CREATE INDEX ix_refresh_sessions_user_active
    ON refresh_sessions (user_id, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX ix_refresh_sessions_family ON refresh_sessions (family_id);

CREATE TABLE password_reset_challenges (
    challenge_id     UUID PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    otp_digest       CHAR(64) NOT NULL,
    purpose          VARCHAR(30) NOT NULL DEFAULT 'PASSWORD_RESET',
    expires_at       TIMESTAMPTZ NOT NULL,
    attempts         SMALLINT NOT NULL DEFAULT 0,
    consumed_at      TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_password_reset_challenges_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT ck_password_reset_attempts CHECK (attempts >= 0 AND attempts <= 10),
    CONSTRAINT ck_password_reset_purpose CHECK (purpose = 'PASSWORD_RESET')
);

CREATE INDEX ix_password_reset_challenges_user_active
    ON password_reset_challenges (user_id, expires_at)
    WHERE consumed_at IS NULL;

CREATE TABLE external_identities (
    external_identity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL,
    provider              VARCHAR(30) NOT NULL,
    provider_subject      VARCHAR(255) NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_external_identities_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uq_external_identity_subject UNIQUE (provider, provider_subject),
    CONSTRAINT uq_external_identity_user_provider UNIQUE (user_id, provider),
    CONSTRAINT ck_external_identity_provider CHECK (provider IN ('GOOGLE'))
);

-- V1 modeled raw identity and face vectors. The approved baseline removes those
-- irreversible identifiers and retains only verification metrics.
DROP INDEX IF EXISTS ix_seller_biometrics_embedding;
DROP INDEX IF EXISTS ix_seller_biometrics_cccd;
ALTER TABLE seller_biometrics DROP CONSTRAINT IF EXISTS uq_seller_biometrics_cccd;
ALTER TABLE seller_biometrics DROP CONSTRAINT IF EXISTS uq_seller_biometrics_user;
ALTER TABLE seller_biometrics DROP COLUMN cccd_number;
ALTER TABLE seller_biometrics DROP COLUMN full_name;
ALTER TABLE seller_biometrics DROP COLUMN dob;
ALTER TABLE seller_biometrics DROP COLUMN hometown;
ALTER TABLE seller_biometrics DROP COLUMN address;
ALTER TABLE seller_biometrics DROP COLUMN face_embedding;
ALTER TABLE seller_biometrics DROP COLUMN card_front_url;
ALTER TABLE seller_biometrics DROP COLUMN selfie_photo_url;
ALTER TABLE seller_biometrics RENAME COLUMN biometric_id TO metric_id;
ALTER TABLE seller_biometrics RENAME COLUMN created_at TO processed_at;
ALTER TABLE seller_biometrics RENAME TO seller_verification_metrics;
ALTER INDEX ix_seller_biometrics_user_id RENAME TO ix_seller_verification_metrics_user_id;
ALTER TABLE seller_verification_metrics
    ADD COLUMN threshold_used NUMERIC(5,4),
    ADD COLUMN model_name VARCHAR(80) NOT NULL DEFAULT 'ArcFace',
    ADD COLUMN model_version VARCHAR(80) NOT NULL DEFAULT 'demo-baseline',
    ADD COLUMN is_simulated BOOLEAN NOT NULL DEFAULT TRUE,
    ADD CONSTRAINT uq_seller_verification_metrics_verification UNIQUE (verification_id);

ALTER TABLE seller_verifications DROP CONSTRAINT ck_seller_verifications_resolution;
ALTER TABLE seller_verifications ADD CONSTRAINT ck_seller_verifications_resolution CHECK (
    (status = 'PENDING' AND reviewed_at IS NULL AND verified_by IS NULL AND rejection_reason IS NULL)
    OR
    (status = 'VERIFIED' AND reviewed_at IS NOT NULL AND rejection_reason IS NULL
        AND (
            (verification_method = 'AI_EKYC' AND verified_by IS NULL)
            OR (verification_method = 'MANUAL_ID_DOCUMENT' AND verified_by IS NOT NULL)
        ))
    OR
    (status = 'REJECTED' AND reviewed_at IS NOT NULL AND rejection_reason IS NOT NULL)
);
