-- Pricing, negotiation, chat-read model and transactional event baseline.
-- PostgreSQL remains the source of truth; Redis/WebSocket consumers are fed
-- from the outbox after the owning transaction commits.

-- ---------------------------------------------------------------------------
-- 1. Versioned system-fee policy and explicit seller-listed price
-- ---------------------------------------------------------------------------

CREATE TABLE system_fee_policies (
    fee_policy_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_code            VARCHAR(50) NOT NULL,
    policy_name            VARCHAR(120) NOT NULL,
    buyer_fee_rate         NUMERIC(9,6) NOT NULL DEFAULT 0,
    buyer_fixed_fee        NUMERIC(19,2) NOT NULL DEFAULT 0,
    seller_fee_rate        NUMERIC(9,6) NOT NULL DEFAULT 0,
    seller_fixed_fee       NUMERIC(19,2) NOT NULL DEFAULT 0,
    minimum_buyer_fee      NUMERIC(19,2),
    maximum_buyer_fee      NUMERIC(19,2),
    minimum_seller_fee     NUMERIC(19,2),
    maximum_seller_fee     NUMERIC(19,2),
    rounding_scale         SMALLINT NOT NULL DEFAULT 0,
    rounding_mode          VARCHAR(20) NOT NULL DEFAULT 'HALF_UP',
    currency               CHAR(3) NOT NULL DEFAULT 'VND',
    status                 VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    version                INTEGER NOT NULL,
    effective_from         TIMESTAMPTZ NOT NULL,
    effective_to           TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by             BIGINT,

    CONSTRAINT uq_system_fee_policies_code UNIQUE (policy_code),
    CONSTRAINT uq_system_fee_policies_version UNIQUE (version),
    CONSTRAINT fk_system_fee_policies_created_by FOREIGN KEY (created_by) REFERENCES users (user_id),
    CONSTRAINT ck_system_fee_policies_rates CHECK (
        buyer_fee_rate BETWEEN 0 AND 1 AND seller_fee_rate BETWEEN 0 AND 1
    ),
    CONSTRAINT ck_system_fee_policies_fixed_fees CHECK (
        buyer_fixed_fee >= 0 AND seller_fixed_fee >= 0
    ),
    CONSTRAINT ck_system_fee_policies_buyer_bounds CHECK (
        (minimum_buyer_fee IS NULL OR minimum_buyer_fee >= 0)
        AND (maximum_buyer_fee IS NULL OR maximum_buyer_fee >= 0)
        AND (
            minimum_buyer_fee IS NULL
            OR maximum_buyer_fee IS NULL
            OR minimum_buyer_fee <= maximum_buyer_fee
        )
    ),
    CONSTRAINT ck_system_fee_policies_seller_bounds CHECK (
        (minimum_seller_fee IS NULL OR minimum_seller_fee >= 0)
        AND (maximum_seller_fee IS NULL OR maximum_seller_fee >= 0)
        AND (
            minimum_seller_fee IS NULL
            OR maximum_seller_fee IS NULL
            OR minimum_seller_fee <= maximum_seller_fee
        )
    ),
    CONSTRAINT ck_system_fee_policies_rounding CHECK (
        rounding_scale BETWEEN 0 AND 2 AND rounding_mode IN ('HALF_UP', 'HALF_EVEN', 'DOWN', 'UP')
    ),
    CONSTRAINT ck_system_fee_policies_currency CHECK (currency = 'VND'),
    CONSTRAINT ck_system_fee_policies_status CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    CONSTRAINT ck_system_fee_policies_version CHECK (version > 0),
    CONSTRAINT ck_system_fee_policies_effective_window CHECK (
        effective_to IS NULL OR effective_to > effective_from
    )
);

CREATE UNIQUE INDEX uq_system_fee_policies_one_active
    ON system_fee_policies (status)
    WHERE status = 'ACTIVE';

INSERT INTO system_fee_policies (
    policy_code,
    policy_name,
    buyer_fee_rate,
    buyer_fixed_fee,
    seller_fee_rate,
    seller_fixed_fee,
    rounding_scale,
    rounding_mode,
    currency,
    status,
    version,
    effective_from
) VALUES (
    'DEFAULT_ZERO_V1',
    'Compatibility policy with no system fee',
    0,
    0,
    0,
    0,
    0,
    'HALF_UP',
    'VND',
    'ACTIVE',
    1,
    TIMESTAMPTZ '1970-01-01 00:00:00+00'
);

ALTER TABLE products RENAME COLUMN price TO listed_price;
ALTER TABLE products RENAME CONSTRAINT ck_products_price TO ck_products_listed_price;
ALTER TABLE products
    ADD CONSTRAINT uq_products_id_seller UNIQUE (product_id, seller_id);

-- ---------------------------------------------------------------------------
-- 2. Conversation product snapshot and stable inbox ordering
-- ---------------------------------------------------------------------------

ALTER TABLE conversations
    ADD COLUMN product_title_snapshot VARCHAR(200),
    ADD COLUMN product_price_at_start NUMERIC(19,2),
    ADD COLUMN product_thumbnail_snapshot TEXT,
    ADD COLUMN currency CHAR(3),
    ADD COLUMN last_message_id BIGINT,
    ADD COLUMN last_activity_at TIMESTAMPTZ,
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN closed_at TIMESTAMPTZ;

UPDATE conversations AS conversation
SET product_title_snapshot = product.title,
    product_price_at_start = product.listed_price,
    product_thumbnail_snapshot = (
        SELECT media.media_url
        FROM product_media AS media
        WHERE media.product_id = product.product_id
          AND media.media_type = 'IMAGE'
        ORDER BY media.display_order, media.media_id
        LIMIT 1
    ),
    currency = product.currency,
    last_activity_at = COALESCE(conversation.last_message_at, conversation.created_at)
FROM products AS product
WHERE product.product_id = conversation.product_id;

-- V1 offers did not reference conversations. Preserve them by creating the
-- missing buyer/seller/product conversation before the offer columns change.
INSERT INTO conversations (
    buyer_id,
    seller_id,
    product_id,
    created_at,
    product_title_snapshot,
    product_price_at_start,
    product_thumbnail_snapshot,
    currency,
    last_activity_at
)
SELECT
    legacy_offer.buyer_id,
    legacy_offer.seller_id,
    legacy_offer.product_id,
    MIN(legacy_offer.created_at),
    product.title,
    product.listed_price,
    (
        SELECT media.media_url
        FROM product_media AS media
        WHERE media.product_id = product.product_id
          AND media.media_type = 'IMAGE'
        ORDER BY media.display_order, media.media_id
        LIMIT 1
    ),
    product.currency,
    MAX(legacy_offer.created_at)
FROM offers AS legacy_offer
JOIN products AS product ON product.product_id = legacy_offer.product_id
GROUP BY
    legacy_offer.buyer_id,
    legacy_offer.seller_id,
    legacy_offer.product_id,
    product.product_id,
    product.title,
    product.listed_price,
    product.currency
ON CONFLICT (buyer_id, seller_id, product_id) DO NOTHING;

UPDATE conversations AS conversation
SET last_message_id = (
        SELECT message.message_id
        FROM messages AS message
        WHERE message.conversation_id = conversation.conversation_id
        ORDER BY message.created_at DESC, message.message_id DESC
        LIMIT 1
    );

DROP INDEX ix_conversations_buyer_recent;
DROP INDEX ix_conversations_seller_recent;

ALTER TABLE conversations
    ALTER COLUMN product_title_snapshot SET NOT NULL,
    ALTER COLUMN product_price_at_start SET NOT NULL,
    ALTER COLUMN currency SET NOT NULL,
    ALTER COLUMN last_activity_at SET NOT NULL,
    DROP COLUMN last_message_at,
    ADD CONSTRAINT fk_conversations_product_seller
        FOREIGN KEY (product_id, seller_id) REFERENCES products (product_id, seller_id),
    ADD CONSTRAINT ck_conversations_product_price CHECK (product_price_at_start > 0),
    ADD CONSTRAINT ck_conversations_currency CHECK (currency = 'VND'),
    ADD CONSTRAINT ck_conversations_status CHECK (status IN ('ACTIVE', 'CLOSED', 'BLOCKED')),
    ADD CONSTRAINT ck_conversations_closed_state CHECK (
        (status = 'CLOSED' AND closed_at IS NOT NULL)
        OR (status <> 'CLOSED' AND closed_at IS NULL)
    );

CREATE INDEX ix_conversations_buyer_activity
    ON conversations (buyer_id, last_activity_at DESC, conversation_id DESC);
CREATE INDEX ix_conversations_seller_activity
    ON conversations (seller_id, last_activity_at DESC, conversation_id DESC);

-- ---------------------------------------------------------------------------
-- 3. Idempotent messages and per-participant read cursor
-- ---------------------------------------------------------------------------

ALTER TABLE messages
    ADD COLUMN client_message_id UUID,
    ADD COLUMN reply_to_message_id BIGINT,
    ADD COLUMN edited_at TIMESTAMPTZ,
    ADD COLUMN deleted_at TIMESTAMPTZ;

UPDATE messages SET client_message_id = gen_random_uuid();

ALTER TABLE messages DROP CONSTRAINT ck_messages_type;
ALTER TABLE messages DROP CONSTRAINT ck_messages_read_time;
ALTER TABLE messages DROP COLUMN read_at;
ALTER TABLE messages ALTER COLUMN message_type TYPE VARCHAR(20);
ALTER TABLE messages ALTER COLUMN client_message_id SET NOT NULL;
ALTER TABLE messages
    ADD CONSTRAINT ck_messages_type CHECK (message_type IN ('TEXT', 'IMAGE', 'OFFER', 'SYSTEM')),
    ADD CONSTRAINT ck_messages_edit_time CHECK (edited_at IS NULL OR edited_at >= created_at),
    ADD CONSTRAINT ck_messages_delete_time CHECK (deleted_at IS NULL OR deleted_at >= created_at),
    ADD CONSTRAINT ck_messages_not_self_reply CHECK (
        reply_to_message_id IS NULL OR reply_to_message_id <> message_id
    ),
    ADD CONSTRAINT uq_messages_conversation_client UNIQUE (conversation_id, client_message_id),
    ADD CONSTRAINT uq_messages_conversation_message UNIQUE (conversation_id, message_id),
    ADD CONSTRAINT fk_messages_reply
        FOREIGN KEY (conversation_id, reply_to_message_id)
        REFERENCES messages (conversation_id, message_id);

CREATE TABLE conversation_user_state (
    conversation_id      BIGINT NOT NULL,
    user_id              BIGINT NOT NULL,
    last_read_message_id BIGINT,
    joined_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_read_at         TIMESTAMPTZ,
    muted_at             TIMESTAMPTZ,
    archived_at          TIMESTAMPTZ,

    CONSTRAINT pk_conversation_user_state PRIMARY KEY (conversation_id, user_id),
    CONSTRAINT fk_conversation_user_state_conversation
        FOREIGN KEY (conversation_id) REFERENCES conversations (conversation_id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_user_state_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_conversation_user_state_last_read
        FOREIGN KEY (conversation_id, last_read_message_id)
        REFERENCES messages (conversation_id, message_id),
    CONSTRAINT ck_conversation_user_state_read_time CHECK (
        (last_read_message_id IS NULL AND last_read_at IS NULL)
        OR (last_read_message_id IS NOT NULL AND last_read_at IS NOT NULL)
    )
);

INSERT INTO conversation_user_state (conversation_id, user_id, joined_at)
SELECT conversation_id, buyer_id, created_at FROM conversations
UNION ALL
SELECT conversation_id, seller_id, created_at FROM conversations;

CREATE INDEX ix_conversation_user_state_user
    ON conversation_user_state (user_id, archived_at, conversation_id);

ALTER TABLE messages
    ADD CONSTRAINT fk_messages_participant
        FOREIGN KEY (conversation_id, sender_id)
        REFERENCES conversation_user_state (conversation_id, user_id);

ALTER TABLE conversations
    ADD CONSTRAINT fk_conversations_last_message
        FOREIGN KEY (conversation_id, last_message_id)
        REFERENCES messages (conversation_id, message_id);

-- ---------------------------------------------------------------------------
-- 4. Conversation-scoped immutable offer chain with pricing snapshots
-- ---------------------------------------------------------------------------

DROP INDEX ix_offers_product_status;
DROP INDEX ix_offers_buyer_status;
DROP INDEX ix_offers_seller_status;
DROP INDEX uq_offers_one_pending_per_buyer_product;

ALTER TABLE offers RENAME COLUMN offer_price TO offered_item_price;
ALTER TABLE offers
    ADD COLUMN conversation_id BIGINT,
    ADD COLUMN proposer_id BIGINT,
    ADD COLUMN responded_by BIGINT,
    ADD COLUMN parent_offer_id BIGINT,
    ADD COLUMN fee_policy_id BIGINT,
    ADD COLUMN buyer_system_fee NUMERIC(19,2),
    ADD COLUMN seller_system_fee NUMERIC(19,2),
    ADD COLUMN buyer_subtotal NUMERIC(19,2),
    ADD COLUMN seller_proceeds NUMERIC(19,2),
    ADD COLUMN currency CHAR(3),
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

UPDATE offers AS offer
SET conversation_id = conversation.conversation_id,
    proposer_id = offer.buyer_id,
    responded_by = CASE
        WHEN offer.status IN ('ACCEPTED', 'REJECTED', 'COUNTERED') THEN offer.seller_id
        ELSE NULL
    END,
    fee_policy_id = (
        SELECT policy.fee_policy_id
        FROM system_fee_policies AS policy
        WHERE policy.policy_code = 'DEFAULT_ZERO_V1'
    ),
    buyer_system_fee = 0,
    seller_system_fee = 0,
    buyer_subtotal = offer.offered_item_price,
    seller_proceeds = offer.offered_item_price,
    currency = product.currency
FROM conversations AS conversation
JOIN products AS product ON product.product_id = conversation.product_id
WHERE conversation.buyer_id = offer.buyer_id
  AND conversation.seller_id = offer.seller_id
  AND conversation.product_id = offer.product_id;

ALTER TABLE offers DROP CONSTRAINT fk_offers_product;
ALTER TABLE offers DROP CONSTRAINT fk_offers_buyer;
ALTER TABLE offers DROP CONSTRAINT fk_offers_seller;
ALTER TABLE offers DROP CONSTRAINT ck_offers_distinct_users;
ALTER TABLE offers DROP CONSTRAINT ck_offers_price;
ALTER TABLE offers DROP CONSTRAINT ck_offers_status;
ALTER TABLE offers DROP CONSTRAINT ck_offers_response;
ALTER TABLE offers DROP CONSTRAINT ck_offers_expiry;

ALTER TABLE offers
    ALTER COLUMN conversation_id SET NOT NULL,
    ALTER COLUMN proposer_id SET NOT NULL,
    ALTER COLUMN fee_policy_id SET NOT NULL,
    ALTER COLUMN buyer_system_fee SET NOT NULL,
    ALTER COLUMN seller_system_fee SET NOT NULL,
    ALTER COLUMN buyer_subtotal SET NOT NULL,
    ALTER COLUMN seller_proceeds SET NOT NULL,
    ALTER COLUMN currency SET NOT NULL,
    DROP COLUMN product_id,
    DROP COLUMN buyer_id,
    DROP COLUMN seller_id,
    ADD CONSTRAINT uq_offers_conversation_offer UNIQUE (conversation_id, offer_id),
    ADD CONSTRAINT fk_offers_conversation
        FOREIGN KEY (conversation_id) REFERENCES conversations (conversation_id),
    ADD CONSTRAINT fk_offers_proposer
        FOREIGN KEY (conversation_id, proposer_id)
        REFERENCES conversation_user_state (conversation_id, user_id),
    ADD CONSTRAINT fk_offers_responder
        FOREIGN KEY (conversation_id, responded_by)
        REFERENCES conversation_user_state (conversation_id, user_id),
    ADD CONSTRAINT fk_offers_parent
        FOREIGN KEY (conversation_id, parent_offer_id)
        REFERENCES offers (conversation_id, offer_id),
    ADD CONSTRAINT fk_offers_fee_policy
        FOREIGN KEY (fee_policy_id) REFERENCES system_fee_policies (fee_policy_id),
    ADD CONSTRAINT ck_offers_item_price CHECK (offered_item_price > 0),
    ADD CONSTRAINT ck_offers_fees CHECK (
        buyer_system_fee >= 0
        AND seller_system_fee >= 0
        AND seller_system_fee <= offered_item_price
        AND buyer_subtotal = offered_item_price + buyer_system_fee
        AND seller_proceeds = offered_item_price - seller_system_fee
    ),
    ADD CONSTRAINT ck_offers_currency CHECK (currency = 'VND'),
    ADD CONSTRAINT ck_offers_status CHECK (
        status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'COUNTERED', 'WITHDRAWN', 'EXPIRED')
    ),
    ADD CONSTRAINT ck_offers_response CHECK (
        (status = 'PENDING' AND responded_at IS NULL AND responded_by IS NULL)
        OR
        (status = 'EXPIRED' AND responded_at IS NOT NULL AND responded_by IS NULL)
        OR
        (status = 'WITHDRAWN' AND responded_at IS NOT NULL AND responded_by = proposer_id)
        OR
        (
            status IN ('ACCEPTED', 'REJECTED', 'COUNTERED')
            AND responded_at IS NOT NULL
            AND responded_by IS NOT NULL
            AND responded_by <> proposer_id
        )
    ),
    ADD CONSTRAINT ck_offers_expiry CHECK (expires_at IS NULL OR expires_at > created_at),
    ADD CONSTRAINT ck_offers_not_self_parent CHECK (
        parent_offer_id IS NULL OR parent_offer_id <> offer_id
    );

CREATE INDEX ix_offers_conversation_created
    ON offers (conversation_id, created_at DESC, offer_id DESC);
CREATE INDEX ix_offers_proposer_created
    ON offers (proposer_id, created_at DESC);
CREATE UNIQUE INDEX uq_offers_one_pending_per_conversation
    ON offers (conversation_id)
    WHERE status = 'PENDING';

ALTER TABLE messages
    ADD COLUMN offer_id BIGINT,
    ADD CONSTRAINT fk_messages_offer
        FOREIGN KEY (conversation_id, offer_id)
        REFERENCES offers (conversation_id, offer_id),
    ADD CONSTRAINT uq_messages_offer UNIQUE (offer_id),
    ADD CONSTRAINT ck_messages_offer_reference CHECK (
        (message_type = 'OFFER' AND offer_id IS NOT NULL)
        OR (message_type <> 'OFFER' AND offer_id IS NULL)
    );

-- ---------------------------------------------------------------------------
-- 5. Order pricing snapshots and negotiated-price traceability
-- ---------------------------------------------------------------------------

ALTER TABLE orders DROP CONSTRAINT ck_orders_amounts;
ALTER TABLE orders
    ADD COLUMN buyer_system_fee NUMERIC(19,2),
    ADD COLUMN seller_system_fee NUMERIC(19,2),
    ADD COLUMN seller_proceeds NUMERIC(19,2);

UPDATE orders
SET buyer_system_fee = 0,
    seller_system_fee = 0,
    seller_proceeds = subtotal;

ALTER TABLE orders
    ALTER COLUMN buyer_system_fee SET NOT NULL,
    ALTER COLUMN seller_system_fee SET NOT NULL,
    ALTER COLUMN seller_proceeds SET NOT NULL,
    ADD CONSTRAINT ck_orders_amounts CHECK (
        subtotal > 0
        AND buyer_system_fee >= 0
        AND seller_system_fee >= 0
        AND seller_system_fee <= subtotal
        AND shipping_fee >= 0
        AND seller_proceeds = subtotal - seller_system_fee
        AND total_amount = subtotal + buyer_system_fee + shipping_fee
    );

ALTER TABLE order_items RENAME COLUMN unit_price TO agreed_price;
ALTER TABLE order_items RENAME COLUMN line_total TO buyer_line_total;
ALTER TABLE order_items DROP CONSTRAINT ck_order_items_price;
ALTER TABLE order_items
    ADD COLUMN listed_price NUMERIC(19,2),
    ADD COLUMN buyer_system_fee NUMERIC(19,2),
    ADD COLUMN seller_system_fee NUMERIC(19,2),
    ADD COLUMN seller_line_proceeds NUMERIC(19,2),
    ADD COLUMN fee_policy_id BIGINT,
    ADD COLUMN accepted_offer_id BIGINT,
    ADD COLUMN pricing_source VARCHAR(20) NOT NULL DEFAULT 'LIST_PRICE';

UPDATE order_items
SET listed_price = agreed_price,
    buyer_system_fee = 0,
    seller_system_fee = 0,
    seller_line_proceeds = agreed_price * quantity,
    fee_policy_id = (
        SELECT policy.fee_policy_id
        FROM system_fee_policies AS policy
        WHERE policy.policy_code = 'DEFAULT_ZERO_V1'
    );

ALTER TABLE order_items
    ALTER COLUMN listed_price SET NOT NULL,
    ALTER COLUMN buyer_system_fee SET NOT NULL,
    ALTER COLUMN seller_system_fee SET NOT NULL,
    ALTER COLUMN seller_line_proceeds SET NOT NULL,
    ALTER COLUMN fee_policy_id SET NOT NULL,
    ADD CONSTRAINT fk_order_items_fee_policy
        FOREIGN KEY (fee_policy_id) REFERENCES system_fee_policies (fee_policy_id),
    ADD CONSTRAINT fk_order_items_accepted_offer
        FOREIGN KEY (accepted_offer_id) REFERENCES offers (offer_id),
    ADD CONSTRAINT uq_order_items_accepted_offer UNIQUE (accepted_offer_id),
    ADD CONSTRAINT ck_order_items_prices CHECK (
        listed_price > 0
        AND agreed_price > 0
        AND buyer_system_fee >= 0
        AND seller_system_fee >= 0
        AND seller_system_fee <= agreed_price * quantity
        AND buyer_line_total = agreed_price * quantity + buyer_system_fee
        AND seller_line_proceeds = agreed_price * quantity - seller_system_fee
    ),
    ADD CONSTRAINT ck_order_items_pricing_source CHECK (
        (pricing_source = 'LIST_PRICE' AND accepted_offer_id IS NULL AND agreed_price = listed_price)
        OR (pricing_source = 'OFFER' AND accepted_offer_id IS NOT NULL)
    );

CREATE INDEX ix_order_items_fee_policy ON order_items (fee_policy_id);

-- ---------------------------------------------------------------------------
-- 6. Durable event publication boundary for Redis/WebSocket/notifications
-- ---------------------------------------------------------------------------

CREATE TABLE outbox_events (
    event_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    aggregate_type  VARCHAR(80) NOT NULL,
    aggregate_id    VARCHAR(100) NOT NULL,
    event_type      VARCHAR(120) NOT NULL,
    payload         JSONB NOT NULL,
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    available_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at    TIMESTAMPTZ,
    attempt_count   INTEGER NOT NULL DEFAULT 0,
    last_error      VARCHAR(1000),

    CONSTRAINT ck_outbox_events_payload CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT ck_outbox_events_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_outbox_events_publish_time CHECK (
        published_at IS NULL OR published_at >= occurred_at
    )
);

CREATE INDEX ix_outbox_events_unpublished
    ON outbox_events (available_at, occurred_at, event_id)
    WHERE published_at IS NULL;
CREATE INDEX ix_outbox_events_aggregate
    ON outbox_events (aggregate_type, aggregate_id, occurred_at DESC);
