-- ============================================================================
-- V6: Voucher Engine & Media Lifecycle Baseline
-- - Voucher Engine & Order Discount Invariants
-- - Seller Product Media Guard: at least 1 image and 1 video, max 5 images and 1 video
-- - Buyer Unboxing Evidence: optional with explicit 'SKIPPED_BY_BUYER' audit
-- - Chat Media Quota: scoped per-conversation per-sender per-day (max 5 images, 1 video)
-- - Chat Media Ephemeral Lifecycle: 7-day retention with Dispute Freeze
-- - Complaint Evidence Retention: auto-scheduled cleanup 3 days post-resolution
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Voucher Engine & Order Discount Invariants
-- ---------------------------------------------------------------------------

CREATE TABLE vouchers (
    voucher_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                   VARCHAR(50) NOT NULL,
    title                  VARCHAR(200) NOT NULL,
    description            TEXT,
    voucher_type           VARCHAR(30) NOT NULL,
    discount_type          VARCHAR(20) NOT NULL,
    discount_value         NUMERIC(19,2) NOT NULL,
    max_discount_amount    NUMERIC(19,2),
    min_order_amount       NUMERIC(19,2) NOT NULL DEFAULT 0,
    sponsor_type           VARCHAR(20) NOT NULL DEFAULT 'PLATFORM',
    seller_id              BIGINT,
    total_usage_limit      INTEGER,
    current_usage_count    INTEGER NOT NULL DEFAULT 0,
    max_usage_per_user     INTEGER NOT NULL DEFAULT 1,
    start_time             TIMESTAMPTZ NOT NULL,
    end_time               TIMESTAMPTZ NOT NULL,
    is_active              BOOLEAN NOT NULL DEFAULT TRUE,
    version                BIGINT NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ,

    CONSTRAINT uq_vouchers_code UNIQUE (code),
    CONSTRAINT fk_vouchers_seller FOREIGN KEY (seller_id) REFERENCES users (user_id),
    CONSTRAINT ck_vouchers_code_format CHECK (code = upper(btrim(code))),
    CONSTRAINT ck_vouchers_type CHECK (voucher_type IN ('ORDER_DISCOUNT', 'SHIPPING_DISCOUNT', 'BUYER_FEE_DISCOUNT')),
    CONSTRAINT ck_vouchers_discount_type CHECK (discount_type IN ('FIXED_AMOUNT', 'PERCENTAGE')),
    CONSTRAINT ck_vouchers_discount_value CHECK (
        (discount_type = 'FIXED_AMOUNT' AND discount_value > 0)
        OR
        (discount_type = 'PERCENTAGE' AND discount_value > 0 AND discount_value <= 100)
    ),
    CONSTRAINT ck_vouchers_sponsor CHECK (
        (sponsor_type = 'PLATFORM' AND seller_id IS NULL)
        OR
        (sponsor_type = 'SELLER' AND seller_id IS NOT NULL)
    ),
    CONSTRAINT ck_vouchers_usage CHECK (
        current_usage_count >= 0
        AND (total_usage_limit IS NULL OR current_usage_count <= total_usage_limit)
        AND max_usage_per_user > 0
    ),
    CONSTRAINT ck_vouchers_window CHECK (end_time > start_time)
);

CREATE INDEX ix_vouchers_active_window ON vouchers (is_active, start_time, end_time);
CREATE INDEX ix_vouchers_seller ON vouchers (seller_id) WHERE seller_id IS NOT NULL;

CREATE TABLE order_vouchers (
    order_voucher_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id               BIGINT NOT NULL,
    voucher_id             BIGINT NOT NULL,
    voucher_code_snapshot  VARCHAR(50) NOT NULL,
    voucher_type_snapshot  VARCHAR(30) NOT NULL,
    sponsor_type_snapshot  VARCHAR(20) NOT NULL,
    discount_amount        NUMERIC(19,2) NOT NULL,
    applied_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_order_vouchers_order FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT fk_order_vouchers_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers (voucher_id),
    CONSTRAINT uq_order_vouchers_order_voucher UNIQUE (order_id, voucher_id),
    CONSTRAINT ck_order_vouchers_discount CHECK (discount_amount > 0)
);

CREATE INDEX ix_order_vouchers_order ON order_vouchers (order_id);
CREATE INDEX ix_order_vouchers_voucher ON order_vouchers (voucher_id);

ALTER TABLE orders
    ADD COLUMN voucher_discount_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    ADD COLUMN shipping_discount_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    ADD COLUMN sponsor_type VARCHAR(20) NOT NULL DEFAULT 'PLATFORM';

ALTER TABLE orders DROP CONSTRAINT ck_orders_amounts;

ALTER TABLE orders ADD CONSTRAINT ck_orders_amounts CHECK (
    subtotal > 0
    AND buyer_system_fee >= 0
    AND seller_system_fee >= 0
    AND seller_system_fee <= subtotal
    AND shipping_fee >= 0
    AND voucher_discount_amount >= 0
    AND shipping_discount_amount >= 0
    AND shipping_discount_amount <= shipping_fee
    AND (voucher_discount_amount + shipping_discount_amount) < (subtotal + buyer_system_fee + shipping_fee)
    AND seller_proceeds = (
        subtotal 
        - (CASE WHEN sponsor_type = 'SELLER' THEN voucher_discount_amount ELSE 0 END)
        - seller_system_fee
    )
    AND total_amount = subtotal + buyer_system_fee + shipping_fee - voucher_discount_amount - shipping_discount_amount
);

-- Seed MVP platform promotional voucher
INSERT INTO vouchers (
    code,
    title,
    description,
    voucher_type,
    discount_type,
    discount_value,
    max_discount_amount,
    min_order_amount,
    sponsor_type,
    total_usage_limit,
    max_usage_per_user,
    start_time,
    end_time,
    is_active
) VALUES (
    'WELCOMEOG',
    'Giảm ngay 50.000đ cho đơn hàng đầu tiên',
    'Mã giảm giá chào mừng thành viên mới của sàn O.G Shop',
    'ORDER_DISCOUNT',
    'FIXED_AMOUNT',
    50000,
    50000,
    100000,
    'PLATFORM',
    10000,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '1 year',
    TRUE
), (
    'OGFREESHIP',
    'Miễn phí vận chuyển đồng kiểm (tối đa 30.000đ)',
    'Hỗ trợ phí vận chuyển cho đơn hàng từ 200.000đ',
    'SHIPPING_DISCOUNT',
    'FIXED_AMOUNT',
    30000,
    30000,
    200000,
    'PLATFORM',
    50000,
    5,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP + INTERVAL '1 year',
    TRUE
);

-- ---------------------------------------------------------------------------
-- 2. Seller Product Media Guard (Cloudinary Metadata & Strict Guard)
-- ---------------------------------------------------------------------------

ALTER TABLE product_media
    ADD COLUMN thumbnail_url TEXT,
    ADD COLUMN duration_seconds INTEGER,
    ADD COLUMN file_size_bytes BIGINT,
    ADD COLUMN cloudinary_public_id VARCHAR(255),
    ADD COLUMN mime_type VARCHAR(50);

ALTER TABLE product_media ADD CONSTRAINT ck_product_media_duration CHECK (
    duration_seconds IS NULL OR (duration_seconds > 0 AND duration_seconds <= 60)
);

ALTER TABLE product_media ADD CONSTRAINT ck_product_media_file_size CHECK (
    file_size_bytes IS NULL OR (file_size_bytes > 0 AND file_size_bytes <= 52428800) -- 50 MB
);

-- Prevent exceeding maximum 5 images and 1 video per product
CREATE OR REPLACE FUNCTION fn_enforce_product_media_limits()
RETURNS TRIGGER AS $$
DECLARE
    v_image_count INTEGER;
    v_video_count INTEGER;
BEGIN
    SELECT COUNT(*) FILTER (WHERE media_type = 'IMAGE'),
           COUNT(*) FILTER (WHERE media_type = 'VIDEO')
    INTO v_image_count, v_video_count
    FROM product_media
    WHERE product_id = NEW.product_id;

    IF NEW.media_type = 'IMAGE' AND v_image_count >= 5 THEN
        RAISE EXCEPTION 'Mỗi sản phẩm chỉ được đăng tối đa 5 hình ảnh.';
    END IF;

    IF NEW.media_type = 'VIDEO' AND v_video_count >= 1 THEN
        RAISE EXCEPTION 'Mỗi sản phẩm chỉ được đăng tối đa 1 video cận cảnh.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_product_media_limits
BEFORE INSERT ON product_media
FOR EACH ROW
EXECUTE FUNCTION fn_enforce_product_media_limits();

-- Strict publication guard: must have >= 1 image AND >= 1 video to be ACTIVE or PENDING
CREATE OR REPLACE FUNCTION fn_check_product_media_requirements()
RETURNS TRIGGER AS $$
DECLARE
    v_image_count INTEGER;
    v_video_count INTEGER;
BEGIN
    IF NEW.status IN ('PENDING', 'ACTIVE') AND (OLD.status IS NULL OR OLD.status = 'DRAFT') THEN
        SELECT COUNT(*) FILTER (WHERE media_type = 'IMAGE'),
               COUNT(*) FILTER (WHERE media_type = 'VIDEO')
        INTO v_image_count, v_video_count
        FROM product_media
        WHERE product_id = NEW.product_id;

        IF v_image_count < 1 THEN
            RAISE EXCEPTION 'Tin đăng phải có ít nhất 1 hình ảnh sản phẩm (media_type=IMAGE).';
        END IF;

        IF v_video_count < 1 THEN
            RAISE EXCEPTION 'Tin đăng đồ cũ phải có ít nhất 1 video quay cận cảnh sản phẩm (media_type=VIDEO).';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_product_media_publish
BEFORE UPDATE OF status ON products
FOR EACH ROW
EXECUTE FUNCTION fn_check_product_media_requirements();

-- ---------------------------------------------------------------------------
-- 3. Buyer Unboxing Evidence (Optional with explicit Skip Audit)
-- ---------------------------------------------------------------------------

CREATE TABLE order_unboxing_evidences (
    evidence_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id               BIGINT NOT NULL UNIQUE,
    buyer_id               BIGINT NOT NULL,
    status                 VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    video_url              TEXT,
    thumbnail_url          TEXT,
    cloudinary_public_id   VARCHAR(255),
    video_duration_sec     INTEGER,
    file_size_bytes        BIGINT,
    recorded_at            TIMESTAMPTZ,
    skipped_at             TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_unboxing_order FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT fk_unboxing_buyer FOREIGN KEY (buyer_id) REFERENCES users (user_id),
    CONSTRAINT ck_unboxing_status CHECK (status IN ('PENDING', 'SUBMITTED', 'SKIPPED_BY_BUYER')),
    CONSTRAINT ck_unboxing_video_duration CHECK (video_duration_sec IS NULL OR (video_duration_sec > 0 AND video_duration_sec <= 180)),
    CONSTRAINT ck_unboxing_file_size CHECK (file_size_bytes IS NULL OR (file_size_bytes > 0 AND file_size_bytes <= 104857600)),
    CONSTRAINT ck_unboxing_state_data CHECK (
        (status = 'PENDING' AND video_url IS NULL AND recorded_at IS NULL AND skipped_at IS NULL)
        OR
        (status = 'SUBMITTED' AND video_url IS NOT NULL AND recorded_at IS NOT NULL AND skipped_at IS NULL)
        OR
        (status = 'SKIPPED_BY_BUYER' AND video_url IS NULL AND skipped_at IS NOT NULL)
    )
);

CREATE INDEX ix_unboxing_order_status ON order_unboxing_evidences (order_id, status);

-- ---------------------------------------------------------------------------
-- 4. Chat Media Support, Quota (5 images + 1 video/day/conversation) & Ephemeral State
-- ---------------------------------------------------------------------------

ALTER TABLE messages DROP CONSTRAINT ck_messages_type;
ALTER TABLE messages ADD CONSTRAINT ck_messages_type
    CHECK (message_type IN ('TEXT', 'IMAGE', 'VIDEO', 'OFFER', 'SYSTEM'));

ALTER TABLE messages
    ADD COLUMN media_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN media_expires_at TIMESTAMPTZ,
    ADD COLUMN cloudinary_public_id VARCHAR(255),
    ADD COLUMN media_metadata JSONB;

ALTER TABLE messages ADD CONSTRAINT ck_messages_media_status
    CHECK (media_status IN ('ACTIVE', 'EXPIRED', 'HOLD_FOR_DISPUTE'));

CREATE INDEX ix_messages_cleanup ON messages (media_status, media_expires_at)
    WHERE media_status = 'ACTIVE' AND media_expires_at IS NOT NULL;

CREATE TABLE chat_media_daily_quotas (
    conversation_id   BIGINT NOT NULL,
    sender_id         BIGINT NOT NULL,
    quota_date        DATE NOT NULL DEFAULT CURRENT_DATE,
    images_sent       SMALLINT NOT NULL DEFAULT 0,
    videos_sent       SMALLINT NOT NULL DEFAULT 0,
    total_bytes_sent  BIGINT NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ,

    CONSTRAINT pk_chat_media_quotas PRIMARY KEY (conversation_id, sender_id, quota_date),
    CONSTRAINT fk_chat_quotas_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (conversation_id),
    CONSTRAINT fk_chat_quotas_sender FOREIGN KEY (sender_id) REFERENCES users (user_id),
    CONSTRAINT ck_chat_quotas_limits CHECK (
        images_sent <= 5 
        AND videos_sent <= 1
        AND total_bytes_sent <= 47185920 -- 45 MB max per conversation per sender per day
    )
);

CREATE INDEX ix_chat_quotas_date ON chat_media_daily_quotas (quota_date);

-- ---------------------------------------------------------------------------
-- 5. Complaint Evidence Retention (Scheduled auto-clean 3 days post-resolution)
-- ---------------------------------------------------------------------------

ALTER TABLE complaints
    ADD COLUMN evidence_cleanup_due_at TIMESTAMPTZ,
    ADD COLUMN evidence_cleaned_at TIMESTAMPTZ;

CREATE OR REPLACE FUNCTION fn_complaint_resolution_schedule_cleanup()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status IN ('RESOLVED', 'REJECTED') AND (OLD.status IS NULL OR OLD.status NOT IN ('RESOLVED', 'REJECTED')) THEN
        IF NEW.resolved_at IS NOT NULL THEN
            NEW.evidence_cleanup_due_at := NEW.resolved_at + INTERVAL '3 days';
        ELSE
            NEW.evidence_cleanup_due_at := CURRENT_TIMESTAMP + INTERVAL '3 days';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_complaint_cleanup_schedule
BEFORE UPDATE OF status ON complaints
FOR EACH ROW
EXECUTE FUNCTION fn_complaint_resolution_schedule_cleanup();

CREATE INDEX ix_complaints_cleanup_due ON complaints (status, evidence_cleanup_due_at)
    WHERE evidence_cleaned_at IS NULL AND evidence_cleanup_due_at IS NOT NULL;
