-- ============================================================================
-- V9: Product Moderation Decisions & Review Flow (UC70)
-- Append-only moderation decisions with reviewer audit, version tracking,
-- idempotency support (command_key), and rejection reason validation.
-- ============================================================================

CREATE TABLE product_moderation_decisions (
    decision_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id         BIGINT NOT NULL,
    reviewer_id        BIGINT NOT NULL,
    decision           VARCHAR(20) NOT NULL,
    reason             VARCHAR(500),
    product_version    BIGINT NOT NULL,
    command_key        VARCHAR(100),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_moderation_decisions_product FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT fk_moderation_decisions_reviewer FOREIGN KEY (reviewer_id) REFERENCES users (user_id),
    CONSTRAINT ck_moderation_decisions_decision CHECK (decision IN ('APPROVED', 'REJECTED')),
    CONSTRAINT ck_moderation_decisions_reason CHECK (
        (decision = 'REJECTED' AND reason IS NOT NULL AND length(trim(reason)) > 0)
        OR (decision = 'APPROVED')
    )
);

CREATE UNIQUE INDEX uq_moderation_decisions_command_key ON product_moderation_decisions (command_key) WHERE command_key IS NOT NULL;
CREATE INDEX ix_moderation_decisions_product_created ON product_moderation_decisions (product_id, created_at DESC);
CREATE INDEX ix_moderation_decisions_reviewer_created ON product_moderation_decisions (reviewer_id, created_at DESC);
